In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
mbti_skills = pd.read_csv('../../static/csv/mbti_skills.csv')
mbti_skills.head()

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"['strategic planning', ' critical thinking', '..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","['leadership', ' decision making', ' managemen..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","['research', ' creative problem solving', ' lo..."
3,4,ENTP,Debater,ENTPs are enthusiastic innovators. They are ad...,"['idea generation', ' innovation', ' adaptabil..."
4,5,INFJ,Advocate,INFJs are empathetic counselors. They are comp...,"['counseling', ' empathy', ' active listening'..."

In [3]:
website_skill = pd.read_csv('../../static/csv/skill_2.csv')
website_skill.head()

   id                  skill
0   1       security analyst
1   2         authentication
2   3  ui/ux design software
3   4        product manager
4   5     testing techniques

In [4]:
# # convert skill_list to list
# mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: x.split(','))
# mbti_skills.head()

In [5]:
# # remove [ ] from skill_list
# mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i.replace('[', '').replace(']', '') for i in x])

In [6]:
# # make  skill_list column lower case
# mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i.lower() for i in x])
# mbti_skills.head()

In [7]:
# # save to csv
# mbti_skills.to_csv('../../static/csv/mbti_skills.csv', index=False)

In [8]:
mbti_skills.sample(3)

,id,mbti,mbti_name,description,skill_list
6,7,INFP,Mediator,INFPs are creative idealists. They are introsp...,"['creative writing', ' artistic expression', '..."
4,5,INFJ,Advocate,INFJs are empathetic counselors. They are comp...,"['counseling', ' empathy', ' active listening'..."
14,15,ISFP,Adventurer,ISFPs are artistic dreamers. They are creative...,"['artistic expression', ' emotional expression..."

In [9]:
type(mbti_skills['skill_list'][0])

str

In [10]:
# use ast to convert string to list
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: ast.literal_eval(x))
mbti_skills.head(3)

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"[strategic planning, critical thinking, data..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","[leadership, decision making, management, s..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","[research, creative problem solving, logic, ..."

In [11]:
# save to csv
mbti_skills.to_csv('../../static/csv/mbti_skills.csv', index=False)

In [12]:
# replace '-' with ' ' in skill_list
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i.replace('-', ' ') for i in x])

In [13]:
# remove skills and skill
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i.replace('skills', '').replace('skill', '') for i in x])

In [14]:
# strip
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i.strip() for i in x])

In [15]:
# remove empty string
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i for i in x if i != ''])

In [16]:
# make all_skills from skill_list
mbti_skills_list = []
for i in mbti_skills['skill_list']:
    mbti_skills_list += i

print(mbti_skills_list)

['strategic planning', 'critical thinking', 'data analysis', 'problem solving', 'leadership', 'decision making', 'management', 'strategic thinking', 'research', 'creative problem solving', 'logic', 'scientific inquiry', 'idea generation', 'innovation', 'adaptability', 'problem solving', 'counseling', 'empathy', 'active listening', 'emotional intelligence', 'leadership', 'relationship building', 'mentorship', 'empathy', 'creative writing', 'artistic expression', 'advocacy', 'empathy', 'creative brainstorming', 'public speaking', 'entrepreneurship', 'adaptability', 'project management', 'data analysis', 'organization', 'reliability', 'leadership', 'time management', 'process improvement', 'decision making', 'caregiving', 'active listening', 'attention to detail', 'empathy', 'social organizing', 'event planning', 'community building', 'empathy', 'troubleshooting', 'mechanical', 'outdoor activities', 'problem solving', 'risk taking', 'physical activities', 'spontaneous decision making', 'adaptability', 'artistic expression', 'emotional expression', 'individualism', 'creativity', 'entertaining', 'social interactions', 'adaptability', 'spontaneity']

In [17]:
len(mbti_skills_list)

64

In [18]:
# # make it lower case
# all_skills = [skill.lower() for skill in all_skills]

In [19]:
# # from mbti skill_list, combine all skill_list list into one list
# mbti_skill_list = []
# for skill_list in mbti_skills['skill_list']:
#     for skill in skill_list:
#         mbti_skill_list.append(skill)

# mbti_skill_list

In [20]:
# # remove space at front and back of skill
mbti_skills_list = [skill.strip() for skill in mbti_skills_list]
mbti_skills_list

['strategic planning',
 'critical thinking',
 'data analysis',
 'problem solving',
 'leadership',
 'decision making',
 'management',
 'strategic thinking',
 'research',
 'creative problem solving',
 'logic',
 'scientific inquiry',
 'idea generation',
 'innovation',
 'adaptability',
 'problem solving',
 'counseling',
 'empathy',
 'active listening',
 'emotional intelligence',
 'leadership',
 'relationship building',
 'mentorship',
 'empathy',
 'creative writing',
 'artistic expression',
 'advocacy',
 'empathy',
 'creative brainstorming',
 'public speaking',
 'entrepreneurship',
 'adaptability',
 'project management',
 'data analysis',
 'organization',
 'reliability',
 'leadership',
 'time management',
 'process improvement',
 'decision making',
 'caregiving',
 'active listening',
 'attention to detail',
 'empathy',
 'social organizing',
 'event planning',
 'community building',
 'empathy',
 'troubleshooting',
 'mechanical',
 'outdoor activities',
 'problem solving',
 'risk taking',
 'physical activities',
 'spontaneous decision making',
 'adaptability',
 'artistic expression',
 'emotional expression',
 'individualism',
 'creativity',
 'entertaining',
 'social interactions',
 'adaptability',
 'spontaneity']

In [21]:
# # convert to small letter
# #mbti_skill_list = [skill.lower() for skill in all_skills]

# # on mbti_skill, convert also to small letter
# mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i.lower() for i in x])
# mbti_skills.head()

In [22]:
# on website_skill, contain the skill into a list
# get the skill value of all rows in the 'skill' column
website_skill_list = website_skill['skill'].to_list()
website_skill_list

['security analyst',
 'authentication',
 'ui/ux design software',
 'product manager',
 'testing techniques',
 'content organization',
 'data analysis',
 'authentication methods',
 'user centered design',
 'penetration testing',
 'data protection',
 'testing methods',
 'mvp',
 'sql',
 'scrum master',
 'lean startup',
 'role of a software architect',
 'design ethics',
 'defect detection',
 'black box testing',
 'software development lifecycle',
 'feature prioritization',
 'statistical analysis',
 'unit testing',
 'security incident handling',
 'acceptance criteria',
 'android development',
 'color psychology',
 'devops',
 'information hierarchy',
 'data management',
 'inclusive design',
 'design guidelines',
 'usability testing',
 'software architecture',
 'nosql',
 'agile development',
 'testing existing functionality',
 'user feedback',
 'visual perception',
 'data visualization',
 'database management',
 'restful api',
 'biometric authentication',
 'quality assurance',
 'testing changes',
 'complementary colors',
 'test automation tools',
 'testing metrics',
 'prototyping',
 'user experience',
 'risk taking',
 'design tools',
 'ethical data use',
 'ui/ux design',
 'code review',
 'agile principles',
 'cybersecurity',
 'product launch',
 'responsible ai',
 'data cleaning',
 'software development',
 'stress testing',
 'performance evaluation',
 'product management',
 'device protection',
 'user interface',
 'code coverage',
 'user experience testing',
 'cross platform testing',
 'user acceptance testing',
 'automation',
 'product roadmap',
 'identity verification',
 'data quality',
 'vulnerability identification',
 'pattern recognition',
 'testing phases',
 'iterative development',
 'learning culture',
 'big data',
 'information security',
 'performance testing',
 'lean product development',
 'environment compatibility',
 'product development',
 'scrum framework',
 'adaptability in development',
 'svn',
 'two factor authentication',
 'statistics',
 'color theory',
 'wireframing',
 'authorization',
 'ci/cd',
 'agile software development',
 'data science',
 'usability evaluation',
 'information security compliance',
 'data dashboards',
 'vulnerability management',
 'testing processes',
 'web services',
 'knowledge transfer',
 'security principles',
 'agile methodology',
 'typography',
 'stakeholder collaboration',
 'technical writer',
 'exploratory data analysis',
 'software testing',
 'user verification',
 'organizational security',
 'git',
 'agile manifesto',
 'code quality',
 'data processing',
 'information architecture',
 'access control',
 'load testing',
 'lean thinking',
 'social engineering',
 'security assessment',
 'data preprocessing',
 'api design',
 'collaborative development',
 'api',
 'iterative design',
 'interaction design',
 'version control',
 'security controls',
 'software quality assurance',
 'model performance',
 'software development life cycle',
 'code reusability',
 'tableau',
 'machine learning',
 'incident management',
 'web design',
 'empathy in design',
 'collaboration',
 'continuous integration',
 'mobile responsiveness',
 'endpoint security',
 'data scientist',
 'software integration',
 'product owner',
 'brand identity',
 'data governance',
 'java programming',
 'data ethics',
 'information manipulation',
 'build stability',
 'data analytics',
 'software development practices',
 'cybersecurity threats',
 'compatibility testing',
 'smoke testing',
 'object oriented design',
 'user navigation',
 'user personas',
 'automated testing',
 'test comprehensiveness',
 'emotional design',
 'regression testing',
 'product goals',
 'a/b testing',
 'fail cheap',
 'security measures',
 'graphic design',
 'customer feedback',
 'user interface design',
 'usability principles',
 'product success',
 'median',
 'documentation',
 'solid principles',
 'visual communication',
 'consistency in design',
 'code maintainability',
 'security policy',
 'interactive design',
 'mobile app development',
 'design principles',
 'user experience optimization',
 'data dictionary',
 'data security',
 'threat mitigation',
 'feature evaluation',
 'scrum',
 'design process',
 'dry principle',
 'software development process',
 'exploratory testing',
 'privacy',
 'experimentation',
 'testing efficiency',
 'software development principles',
 'database querying',
 'continuous improvement',
 'network security',
 'account security',
 'user testing',
 'phishing attacks',
 'security incident response plan',
 'identity management',
 'accessibility',
 'source code management',
 'ux design',
 'color schemes',
 'product documentation',
 'user interfaces',
 'animation',
 'feature engineering',
 'metadata',
 'scrum roles',
 'defect identification',
 'innovation',
 'data driven decision making',
 'compliance',
 'predictive modeling',
 'product backlog',
 'fail fast',
 'product strategy',
 'usability',
 'testing extremes',
 'responsive design',
 'product planning',
 'agile practices',
 'test engineer',
 'motion design',
 'multimedia content creation',
 'advanced software engineering',
 'technical communication',
 'research methods',
 'problem solving',
 'professional ethics',
 'artificial intelligence',
 'software engineering',
 'back end',
 'data structures',
 'entrepreneurship',
 'algorithm design',
 'modeling',
 'advanced information security',
 'ai foundations',
 'administration',
 'databases',
 'complexity analysis',
 'management principles',
 'technology integration',
 'technology business',
 'assembly language',
 'professional development',
 'hardware',
 'social issues',
 'software design',
 'advanced mathematics',
 'application design',
 'computer architecture',
 'automata theory',
 'network protocols',
 'computing ethics',
 'multimedia technologies',
 'network management',
 'networking',
 'front end',
 'system integration',
 'solution design',
 'web development',
 'system administration',
 'engineering',
 'algorithms',
 'it infrastructure',
 'language design',
 'simulation',
 'logic design',
 'ethical decision making',
 'coding',
 'it industry',
 'network administration',
 'information organization',
 'research methodology',
 'computer science',
 'language theory',
 'digital circuits',
 'integrative programming',
 'architecture design',
 'emerging technologies',
 'mathematics',
 'system architecture',
 'operating systems',
 'programming languages',
 'interface design',
 'maintenance',
 'quantitative analysis',
 'formal languages',
 'optimization',
 'syntax',
 'it support',
 'systems analysis',
 'presentation ',
 'thesis development',
 'research planning',
 'project management',
 'leadership',
 'structured programming',
 'design',
 'data communication',
 'application development',
 'electronics',
 'analysis',
 'advanced programming',
 'research writing',
 'organizational management',
 'programming']

In [23]:
# on mbti_skill_list, remove the skill that already exist in all__existing_skills
mbti_unique_skill_list = [skill for skill in mbti_skills_list if skill not in website_skill_list]
mbti_unique_skill_list

['strategic planning',
 'critical thinking',
 'decision making',
 'management',
 'strategic thinking',
 'research',
 'creative problem solving',
 'logic',
 'scientific inquiry',
 'idea generation',
 'adaptability',
 'counseling',
 'empathy',
 'active listening',
 'emotional intelligence',
 'relationship building',
 'mentorship',
 'empathy',
 'creative writing',
 'artistic expression',
 'advocacy',
 'empathy',
 'creative brainstorming',
 'public speaking',
 'adaptability',
 'organization',
 'reliability',
 'time management',
 'process improvement',
 'decision making',
 'caregiving',
 'active listening',
 'attention to detail',
 'empathy',
 'social organizing',
 'event planning',
 'community building',
 'empathy',
 'troubleshooting',
 'mechanical',
 'outdoor activities',
 'physical activities',
 'spontaneous decision making',
 'adaptability',
 'artistic expression',
 'emotional expression',
 'individualism',
 'creativity',
 'entertaining',
 'social interactions',
 'adaptability',
 'spontaneity']

In [24]:
print(len(mbti_unique_skill_list))

52

In [25]:
# remove duplicate
mbti_unique_skill_list = list(set(mbti_unique_skill_list))

In [26]:
# # convert the list of unique skills to a DataFrame
skills_df = pd.DataFrame(mbti_unique_skill_list, columns=['skill'])
skills_df.head()

               skill
0   active listening
1         mentorship
2   creative writing
3  social organizing
4           research

In [27]:
# get last id of skill
last_id = website_skill['id'].max()
last_id

316

In [28]:
# add id to skills_df
skills_df['id'] = skills_df.index + last_id + 1
# reorder
skills_df = skills_df[['id', 'skill']]
skills_df.head()

    id              skill
0  317   active listening
1  318         mentorship
2  319   creative writing
3  320  social organizing
4  321           research

In [29]:
website_skill.tail(3)

      id                      skill
313  314           research writing
314  315  organizational management
315  316                programming

In [30]:
# combine skills_df and website_skill
website_skill = pd.concat([website_skill, skills_df])
website_skill.tail()

     id                skill
37  354   strategic planning
38  355  attention to detail
39  356       event planning
40  357           mechanical
41  358             advocacy

In [31]:
# reset index
website_skill.reset_index(drop=True, inplace=True)
website_skill.tail()

      id                skill
353  354   strategic planning
354  355  attention to detail
355  356       event planning
356  357           mechanical
357  358             advocacy

In [32]:
# save to csv
website_skill.to_csv('../../static/csv/skill_3.csv', index=False)

# MBTI Skill Mapping

In [33]:
import numpy as np
import pandas as pd
import ast

In [34]:
# load skill_3.csv
website_skill = pd.read_csv('../../static/csv/skill_3.csv')
website_skill.head(3)

   id                  skill
0   1       security analyst
1   2         authentication
2   3  ui/ux design software

In [35]:
# load mbti_skills.csv
mbti_skills = pd.read_csv('../../static/csv/mbti_skills.csv')
mbti_skills.head(3)

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"['strategic planning', ' critical thinking', '..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","['leadership', ' decision making', ' managemen..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","['research', ' creative problem solving', ' lo..."

# sjhfalsshad

In [36]:
# use ast to convert string to list
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: ast.literal_eval(x))

In [37]:
# convert skill_list to mbti_skill_list
mbti_skill_list = []
for i in mbti_skills['skill_list']:
    mbti_skill_list += i

mbti_skill_list

['strategic planning',
 ' critical thinking',
 ' data analysis',
 ' problem solving',
 'leadership',
 ' decision making',
 ' management',
 ' strategic thinking',
 'research',
 ' creative problem solving',
 ' logic',
 ' scientific inquiry',
 'idea generation',
 ' innovation',
 ' adaptability',
 ' problem solving',
 'counseling',
 ' empathy',
 ' active listening',
 ' emotional intelligence',
 'leadership',
 ' relationship building',
 ' mentorship',
 ' empathy',
 'creative writing',
 ' artistic expression',
 ' advocacy',
 ' empathy',
 'creative brainstorming',
 ' public speaking',
 ' entrepreneurship',
 ' adaptability',
 'project management',
 ' data analysis',
 ' organization',
 ' reliability',
 'leadership',
 ' time management',
 ' process improvement',
 ' decision making',
 'caregiving',
 ' active listening',
 ' attention to detail',
 ' empathy',
 'social organizing',
 ' event planning',
 ' community building',
 ' empathy',
 'troubleshooting',
 ' mechanical skills',
 ' outdoor activities',
 ' problem solving',
 'risk taking',
 ' physical activities',
 ' spontaneous decision making',
 ' adaptability',
 'artistic expression',
 ' emotional expression',
 ' individualism',
 ' creativity',
 'entertaining',
 ' social interactions',
 ' adaptability',
 ' spontaneity']

In [38]:
# strip space at front and back of skill
mbti_skill_list = [skill.strip() for skill in mbti_skill_list]
mbti_skill_list

['strategic planning',
 'critical thinking',
 'data analysis',
 'problem solving',
 'leadership',
 'decision making',
 'management',
 'strategic thinking',
 'research',
 'creative problem solving',
 'logic',
 'scientific inquiry',
 'idea generation',
 'innovation',
 'adaptability',
 'problem solving',
 'counseling',
 'empathy',
 'active listening',
 'emotional intelligence',
 'leadership',
 'relationship building',
 'mentorship',
 'empathy',
 'creative writing',
 'artistic expression',
 'advocacy',
 'empathy',
 'creative brainstorming',
 'public speaking',
 'entrepreneurship',
 'adaptability',
 'project management',
 'data analysis',
 'organization',
 'reliability',
 'leadership',
 'time management',
 'process improvement',
 'decision making',
 'caregiving',
 'active listening',
 'attention to detail',
 'empathy',
 'social organizing',
 'event planning',
 'community building',
 'empathy',
 'troubleshooting',
 'mechanical skills',
 'outdoor activities',
 'problem solving',
 'risk taking',
 'physical activities',
 'spontaneous decision making',
 'adaptability',
 'artistic expression',
 'emotional expression',
 'individualism',
 'creativity',
 'entertaining',
 'social interactions',
 'adaptability',
 'spontaneity']

# sjhfalsshad

In [39]:
# convert website_skill to dictionary
# skill_mapping = unique_skills_df.set_index('skill')['id'].to_dict()
website_skill_dict = website_skill.set_index('skill')['id'].to_dict()

In [40]:
# create dictionary of skill and id
website_skill_dict

{'security analyst': 1,
 'authentication': 2,
 'ui/ux design software': 3,
 'product manager': 4,
 'testing techniques': 5,
 'content organization': 6,
 'data analysis': 7,
 'authentication methods': 8,
 'user centered design': 9,
 'penetration testing': 10,
 'data protection': 11,
 'testing methods': 12,
 'mvp': 13,
 'sql': 14,
 'scrum master': 15,
 'lean startup': 16,
 'role of a software architect': 17,
 'design ethics': 18,
 'defect detection': 19,
 'black box testing': 20,
 'software development lifecycle': 21,
 'feature prioritization': 22,
 'statistical analysis': 23,
 'unit testing': 24,
 'security incident handling': 25,
 'acceptance criteria': 26,
 'android development': 27,
 'color psychology': 28,
 'devops': 29,
 'information hierarchy': 30,
 'data management': 31,
 'inclusive design': 32,
 'design guidelines': 33,
 'usability testing': 34,
 'software architecture': 35,
 'nosql': 36,
 'agile development': 37,
 'testing existing functionality': 38,
 'user feedback': 39,
 'visual perception': 40,
 'data visualization': 41,
 'database management': 42,
 'restful api': 43,
 'biometric authentication': 44,
 'quality assurance': 45,
 'testing changes': 46,
 'complementary colors': 47,
 'test automation tools': 48,
 'testing metrics': 49,
 'prototyping': 50,
 'user experience': 51,
 'risk taking': 52,
 'design tools': 53,
 'ethical data use': 54,
 'ui/ux design': 55,
 'code review': 56,
 'agile principles': 57,
 'cybersecurity': 58,
 'product launch': 59,
 'responsible ai': 60,
 'data cleaning': 61,
 'software development': 62,
 'stress testing': 63,
 'performance evaluation': 64,
 'product management': 65,
 'device protection': 66,
 'user interface': 67,
 'code coverage': 68,
 'user experience testing': 69,
 'cross platform testing': 70,
 'user acceptance testing': 71,
 'automation': 72,
 'product roadmap': 73,
 'identity verification': 74,
 'data quality': 75,
 'vulnerability identification': 76,
 'pattern recognition': 77,
 'testing phases': 78,
 'iterative development': 79,
 'learning culture': 80,
 'big data': 81,
 'information security': 82,
 'performance testing': 83,
 'lean product development': 84,
 'environment compatibility': 85,
 'product development': 86,
 'scrum framework': 87,
 'adaptability in development': 88,
 'svn': 89,
 'two factor authentication': 90,
 'statistics': 91,
 'color theory': 92,
 'wireframing': 93,
 'authorization': 94,
 'ci/cd': 95,
 'agile software development': 96,
 'data science': 97,
 'usability evaluation': 98,
 'information security compliance': 99,
 'data dashboards': 100,
 'vulnerability management': 101,
 'testing processes': 102,
 'web services': 103,
 'knowledge transfer': 104,
 'security principles': 105,
 'agile methodology': 106,
 'typography': 107,
 'stakeholder collaboration': 108,
 'technical writer': 109,
 'exploratory data analysis': 110,
 'software testing': 111,
 'user verification': 112,
 'organizational security': 113,
 'git': 114,
 'agile manifesto': 115,
 'code quality': 116,
 'data processing': 117,
 'information architecture': 118,
 'access control': 119,
 'load testing': 120,
 'lean thinking': 121,
 'social engineering': 122,
 'security assessment': 123,
 'data preprocessing': 124,
 'api design': 125,
 'collaborative development': 126,
 'api': 127,
 'iterative design': 128,
 'interaction design': 129,
 'version control': 130,
 'security controls': 131,
 'software quality assurance': 132,
 'model performance': 133,
 'software development life cycle': 134,
 'code reusability': 135,
 'tableau': 136,
 'machine learning': 137,
 'incident management': 138,
 'web design': 139,
 'empathy in design': 140,
 'collaboration': 141,
 'continuous integration': 142,
 'mobile responsiveness': 143,
 'endpoint security': 144,
 'data scientist': 145,
 'software integration': 146,
 'product owner': 147,
 'brand identity': 148,
 'data governance': 149,
 'java programming': 150,
 'data ethics': 151,
 'information manipulation': 152,
 'build stability': 153,
 'data analytics': 154,
 'software development practices': 155,
 'cybersecurity threats': 156,
 'compatibility testing': 157,
 'smoke testing': 158,
 'object oriented design': 159,
 'user navigation': 160,
 'user personas': 161,
 'automated testing': 162,
 'test comprehensiveness': 163,
 'emotional design': 164,
 'regression testing': 165,
 'product goals': 166,
 'a/b testing': 167,
 'fail cheap': 168,
 'security measures': 169,
 'graphic design': 170,
 'customer feedback': 171,
 'user interface design': 172,
 'usability principles': 173,
 'product success': 174,
 'median': 175,
 'documentation': 176,
 'solid principles': 177,
 'visual communication': 178,
 'consistency in design': 179,
 'code maintainability': 180,
 'security policy': 181,
 'interactive design': 182,
 'mobile app development': 183,
 'design principles': 184,
 'user experience optimization': 185,
 'data dictionary': 186,
 'data security': 187,
 'threat mitigation': 188,
 'feature evaluation': 189,
 'scrum': 190,
 'design process': 191,
 'dry principle': 192,
 'software development process': 193,
 'exploratory testing': 194,
 'privacy': 195,
 'experimentation': 196,
 'testing efficiency': 197,
 'software development principles': 198,
 'database querying': 199,
 'continuous improvement': 200,
 'network security': 201,
 'account security': 202,
 'user testing': 203,
 'phishing attacks': 204,
 'security incident response plan': 205,
 'identity management': 206,
 'accessibility': 207,
 'source code management': 208,
 'ux design': 209,
 'color schemes': 210,
 'product documentation': 211,
 'user interfaces': 212,
 'animation': 213,
 'feature engineering': 214,
 'metadata': 215,
 'scrum roles': 216,
 'defect identification': 217,
 'innovation': 218,
 'data driven decision making': 219,
 'compliance': 220,
 'predictive modeling': 221,
 'product backlog': 222,
 'fail fast': 223,
 'product strategy': 224,
 'usability': 225,
 'testing extremes': 226,
 'responsive design': 227,
 'product planning': 228,
 'agile practices': 229,
 'test engineer': 230,
 'motion design': 231,
 'multimedia content creation': 232,
 'advanced software engineering': 233,
 'technical communication': 234,
 'research methods': 235,
 'problem solving': 236,
 'professional ethics': 237,
 'artificial intelligence': 238,
 'software engineering': 239,
 'back end': 240,
 'data structures': 241,
 'entrepreneurship': 242,
 'algorithm design': 243,
 'modeling': 244,
 'advanced information security': 245,
 'ai foundations': 246,
 'administration': 247,
 'databases': 248,
 'complexity analysis': 249,
 'management principles': 250,
 'technology integration': 251,
 'technology business': 252,
 'assembly language': 253,
 'professional development': 254,
 'hardware': 255,
 'social issues': 256,
 'software design': 257,
 'advanced mathematics': 258,
 'application design': 259,
 'computer architecture': 260,
 'automata theory': 261,
 'network protocols': 262,
 'computing ethics': 263,
 'multimedia technologies': 264,
 'network management': 265,
 'networking': 266,
 'front end': 267,
 'system integration': 268,
 'solution design': 269,
 'web development': 270,
 'system administration': 271,
 'engineering': 272,
 'algorithms': 273,
 'it infrastructure': 274,
 'language design': 275,
 'simulation': 276,
 'logic design': 277,
 'ethical decision making': 278,
 'coding': 279,
 'it industry': 280,
 'network administration': 281,
 'information organization': 282,
 'research methodology': 283,
 'computer science': 284,
 'language theory': 285,
 'digital circuits': 286,
 'integrative programming': 287,
 'architecture design': 288,
 'emerging technologies': 289,
 'mathematics': 290,
 'system architecture': 291,
 'operating systems': 292,
 'programming languages': 293,
 'interface design': 294,
 'maintenance': 295,
 'quantitative analysis': 296,
 'formal languages': 297,
 'optimization': 298,
 'syntax': 299,
 'it support': 300,
 'systems analysis': 301,
 'presentation ': 302,
 'thesis development': 303,
 'research planning': 304,
 'project management': 305,
 'leadership': 306,
 'structured programming': 307,
 'design': 308,
 'data communication': 309,
 'application development': 310,
 'electronics': 311,
 'analysis': 312,
 'advanced programming': 313,
 'research writing': 314,
 'organizational management': 315,
 'programming': 316,
 'active listening': 317,
 'mentorship': 318,
 'creative writing': 319,
 'social organizing': 320,
 'research': 321,
 'relationship building': 322,
 'caregiving': 323,
 'entertaining': 324,
 'process improvement': 325,
 'spontaneous decision making': 326,
 'logic': 327,
 'organization': 328,
 'counseling': 329,
 'social interactions': 330,
 'creative brainstorming': 331,
 'empathy': 332,
 'emotional intelligence': 333,
 'troubleshooting': 334,
 'spontaneity': 335,
 'public speaking': 336,
 'adaptability': 337,
 'creative problem solving': 338,
 'individualism': 339,
 'strategic thinking': 340,
 'creativity': 341,
 'outdoor activities': 342,
 'idea generation': 343,
 'decision making': 344,
 'scientific inquiry': 345,
 'community building': 346,
 'reliability': 347,
 'critical thinking': 348,
 'time management': 349,
 'artistic expression': 350,
 'emotional expression': 351,
 'management': 352,
 'physical activities': 353,
 'strategic planning': 354,
 'attention to detail': 355,
 'event planning': 356,
 'mechanical': 357,
 'advocacy': 358}

In [41]:
mbti_skills.head(3)

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"[strategic planning, critical thinking, data..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","[leadership, decision making, management, s..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","[research, creative problem solving, logic, ..."

In [42]:
# strip space at front and back of skill
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [skill.strip() for skill in x])

In [43]:
# remove '-' and ' ' from skill
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [skill.replace('-', ' ') for skill in x])

In [44]:
# remve 'skills' and 'skill' from skill
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [skill.replace('skills', '').replace('skill', '') for skill in x])

In [45]:
# remove empty string
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [skill for skill in x if skill != ''])
# strip
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [skill.strip() for skill in x])

In [46]:
# apply skill_mapping to skill_list
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [website_skill_dict[i] for i in x])
mbti_skills.head()

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"[354, 348, 7, 236]"
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","[306, 344, 352, 340]"
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","[321, 338, 327, 345]"
3,4,ENTP,Debater,ENTPs are enthusiastic innovators. They are ad...,"[343, 218, 337, 236]"
4,5,INFJ,Advocate,INFJs are empathetic counselors. They are comp...,"[329, 332, 317, 333]"

In [47]:
# explode
mbti_skills = mbti_skills.explode('skill_list')
# get id, and skill_list
mbti_skills = mbti_skills[['id', 'skill_list']]
mbti_skills.head()

   id skill_list
0   1        354
0   1        348
0   1          7
0   1        236
1   2        306

In [48]:
# rename column
mbti_skills.rename(columns={'skill_list': 'skill_id', 'id':'indicator_id'}, inplace=True)
mbti_skills.sample(2)

    indicator_id skill_id
10            11      323
12            13      334

In [49]:
# reset index
mbti_skills.reset_index(drop=True, inplace=True)

In [50]:
# add id
mbti_skills['id'] = mbti_skills.index + 1
mbti_skills.head(3)

   indicator_id skill_id  id
0             1      354   1
1             1      348   2
2             1        7   3

In [51]:
mbti_skills.tail(3)

    indicator_id skill_id  id
61            16      330  62
62            16      337  63
63            16      335  64

In [52]:
# reoder column
mbti_skills = mbti_skills[['id', 'indicator_id', 'skill_id']]
mbti_skills.head(3)

   id  indicator_id skill_id
0   1             1      354
1   2             1      348
2   3             1        7

In [53]:
# save to csv
mbti_skills.to_csv('../../static/csv/personality_indicator_skills.csv', index=False)