In [18]:
import pandas as pd
import numpy as np
import ast

In [17]:
mbti_skills = pd.read_csv('../../static/csv/mbti_skills.csv')
mbti_skills.head()

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"['strategic planning', ' critical thinking', '..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","['leadership', ' decision making', ' managemen..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","['research', ' creative problem solving', ' lo..."
3,4,ENTP,Debater,ENTPs are enthusiastic innovators. They are ad...,"['idea generation', ' innovation', ' adaptabil..."
4,5,INFJ,Advocate,INFJs are empathetic counselors. They are comp...,"['counseling', ' empathy', ' active listening'..."

In [3]:
website_skill = pd.read_csv('../../static/csv/skill_2.csv')
website_skill.head()

   id                            skill
0   1                quality assurance
1   2  software development principles
2   3  software development life cycle
3   4                agile methodology
4   5                       innovation

In [4]:
# # convert skill_list to list
# mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: x.split(','))
# mbti_skills.head()

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"[['strategic planning', ' critical thinking',..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","[['leadership', ' decision making', ' manage..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","[['research', ' creative problem solving', '..."
3,4,ENTP,Debater,ENTPs are enthusiastic innovators. They are ad...,"[['idea generation', ' innovation', ' adapta..."
4,5,INFJ,Advocate,INFJs are empathetic counselors. They are comp...,"[['counseling', ' empathy', ' active listeni..."

In [34]:
# # remove [ ] from skill_list
# mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i.replace('[', '').replace(']', '') for i in x])

In [10]:
# # make  skill_list column lower case
# mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i.lower() for i in x])
# mbti_skills.head()

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"[[, ', s, t, r, a, t, e, g, i, c, , p, l, a, ..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","[[, ', l, e, a, d, e, r, s, h, i, p, ', ,, , ..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","[[, ', r, e, s, e, a, r, c, h, ', ,, , ', , ..."
3,4,ENTP,Debater,ENTPs are enthusiastic innovators. They are ad...,"[[, ', i, d, e, a, , g, e, n, e, r, a, t, i, ..."
4,5,INFJ,Advocate,INFJs are empathetic counselors. They are comp...,"[[, ', c, o, u, n, s, e, l, i, n, g, ', ,, , ..."

In [41]:
# # save to csv
# mbti_skills.to_csv('../../static/csv/mbti_skills.csv', index=False)

In [13]:
mbti_skills.sample(3)

,id,mbti,mbti_name,description,skill_list
7,8,ENFP,Campaigner,ENFPs are enthusiastic explorers. They are ima...,"['creative brainstorming', ' public speaking',..."
3,4,ENTP,Debater,ENTPs are enthusiastic innovators. They are ad...,"['idea generation', ' innovation', ' adaptabil..."
4,5,INFJ,Advocate,INFJs are empathetic counselors. They are comp...,"['counseling', ' empathy', ' active listening'..."

In [15]:
type(mbti_skills['skill_list'][0])

str

In [19]:
# use ast to convert string to list
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: ast.literal_eval(x))
mbti_skills.head(3)

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"[strategic planning, critical thinking, data..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","[leadership, decision making, management, s..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","[research, creative problem solving, logic, ..."

In [20]:
# save to csv
mbti_skills.to_csv('../../static/csv/mbti_skills.csv', index=False)

In [23]:
# make all_skills from skill_list
mbti_skills_list = []
for i in mbti_skills['skill_list']:
    mbti_skills_list += i

print(mbti_skills_list)

['strategic planning', ' critical thinking', ' data analysis', ' problem solving', 'leadership', ' decision making', ' management', ' strategic thinking', 'research', ' creative problem solving', ' logic', ' scientific inquiry', 'idea generation', ' innovation', ' adaptability', ' problem solving', 'counseling', ' empathy', ' active listening', ' emotional intelligence', 'leadership', ' relationship building', ' mentorship', ' empathy', 'creative writing', ' artistic expression', ' advocacy', ' empathy', 'creative brainstorming', ' public speaking', ' entrepreneurship', ' adaptability', 'project management', ' data analysis', ' organization', ' reliability', 'leadership', ' time management', ' process improvement', ' decision making', 'caregiving', ' active listening', ' attention to detail', ' empathy', 'social organizing', ' event planning', ' community building', ' empathy', 'troubleshooting', ' mechanical skills', ' outdoor activities', ' problem solving', 'risk taking', ' physical activities', ' spontaneous decision making', ' adaptability', 'artistic expression', ' emotional expression', ' individualism', ' creativity', 'entertaining', ' social interactions', ' adaptability', ' spontaneity']

In [21]:
# # make it lower case
# all_skills = [skill.lower() for skill in all_skills]

In [45]:
# # from mbti skill_list, combine all skill_list list into one list
# mbti_skill_list = []
# for skill_list in mbti_skills['skill_list']:
#     for skill in skill_list:
#         mbti_skill_list.append(skill)

# mbti_skill_list

['strategic planning',
 ' critical thinking',
 ' data analysis',
 ' problem solving',
 'leadership',
 ' decision making',
 ' management',
 ' strategic thinking',
 'research',
 ' creative problem solving',
 ' logic',
 ' scientific inquiry',
 'idea generation',
 ' innovation',
 ' adaptability',
 ' problem solving',
 'counseling',
 ' empathy',
 ' active listening',
 ' emotional intelligence',
 'leadership',
 ' relationship building',
 ' mentorship',
 ' empathy',
 'creative writing',
 ' artistic expression',
 ' advocacy',
 ' empathy',
 'creative brainstorming',
 ' public speaking',
 ' entrepreneurship',
 ' adaptability',
 'project management',
 ' data analysis',
 ' organization',
 ' reliability',
 'leadership',
 ' time management',
 ' process improvement',
 ' decision making',
 'caregiving',
 ' active listening',
 ' attention to detail',
 ' empathy',
 'social organizing',
 ' event planning',
 ' community building',
 ' empathy',
 'troubleshooting',
 ' mechanical skills',
 ' outdoor activities',
 ' problem solving',
 'risk taking',
 ' physical activities',
 ' spontaneous decision making',
 ' adaptability',
 'artistic expression',
 ' emotional expression',
 ' individualism',
 ' creativity',
 'entertaining',
 ' social interactions',
 ' adaptability',
 ' spontaneity']

In [46]:
# # remove space at front and back of skill
# mbti_skill_list = [skill.strip() for skill in mbti_skill_list]
# mbti_skill_list

['strategic planning',
 'critical thinking',
 'data analysis',
 'problem solving',
 'leadership',
 'decision making',
 'management',
 'strategic thinking',
 'research',
 'creative problem solving',
 'logic',
 'scientific inquiry',
 'idea generation',
 'innovation',
 'adaptability',
 'problem solving',
 'counseling',
 'empathy',
 'active listening',
 'emotional intelligence',
 'leadership',
 'relationship building',
 'mentorship',
 'empathy',
 'creative writing',
 'artistic expression',
 'advocacy',
 'empathy',
 'creative brainstorming',
 'public speaking',
 'entrepreneurship',
 'adaptability',
 'project management',
 'data analysis',
 'organization',
 'reliability',
 'leadership',
 'time management',
 'process improvement',
 'decision making',
 'caregiving',
 'active listening',
 'attention to detail',
 'empathy',
 'social organizing',
 'event planning',
 'community building',
 'empathy',
 'troubleshooting',
 'mechanical skills',
 'outdoor activities',
 'problem solving',
 'risk taking',
 'physical activities',
 'spontaneous decision making',
 'adaptability',
 'artistic expression',
 'emotional expression',
 'individualism',
 'creativity',
 'entertaining',
 'social interactions',
 'adaptability',
 'spontaneity']

In [47]:
# # convert to small letter
# #mbti_skill_list = [skill.lower() for skill in all_skills]

# # on mbti_skill, convert also to small letter
# mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [i.lower() for i in x])
# mbti_skills.head()

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"[strategic planning, critical thinking, data..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","[leadership, decision making, management, s..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","[research, creative problem solving, logic, ..."
3,4,ENTP,Debater,ENTPs are enthusiastic innovators. They are ad...,"[idea generation, innovation, adaptability, ..."
4,5,INFJ,Advocate,INFJs are empathetic counselors. They are comp...,"[counseling, empathy, active listening, emo..."

In [22]:
# on website_skill, contain the skill into a list
# get the skill value of all rows in the 'skill' column
website_skill_list = website_skill['skill'].to_list()
website_skill_list

['quality assurance',
 'software development principles',
 'software development life cycle',
 'agile methodology',
 'innovation',
 'fail cheap',
 'authentication methods',
 'adaptability in development',
 'inclusive design',
 'product launch',
 'svn',
 'learning culture',
 'ux design',
 'ui/ux design software',
 'software quality assurance',
 'security incident handling',
 'exploratory data analysis',
 'source code management',
 'risk-taking',
 'knowledge transfer',
 'mvp',
 'regression testing',
 'information security compliance',
 'data analytics',
 'statistics',
 'prototyping',
 'color theory',
 'product goals',
 'user-centered design',
 'product management',
 'lean thinking',
 'product documentation',
 'data security',
 'software development process',
 'product backlog',
 'privacy',
 'complementary colors',
 'identity management',
 'security policy',
 'empathy in design',
 'automated testing',
 'feature prioritization',
 'pattern recognition',
 'product planning',
 'wireframing',
 'usability principles',
 'design guidelines',
 'data cleaning',
 'organizational security',
 'design process',
 'tableau',
 'unit testing',
 'sql',
 'cybersecurity',
 'two-factor authentication',
 'design ethics',
 'security principles',
 'data visualization',
 'penetration testing',
 'feature engineering',
 'user verification',
 'scrum master',
 'model performance',
 'consistency in design',
 'database querying',
 'color schemes',
 'user experience testing',
 'restful api',
 'performance evaluation',
 'data management',
 'a/b testing',
 'user experience',
 'android development',
 'user interface',
 'accessibility',
 'data science',
 'smoke testing',
 'data ethics',
 'mobile responsiveness',
 'machine learning',
 'predictive modeling',
 'ui/ux design',
 'endpoint security',
 'data analysis',
 'acceptance criteria',
 'testing metrics',
 'api',
 'defect detection',
 'access control',
 'user experience optimization',
 'threat mitigation',
 'user navigation',
 'authentication',
 'software integration',
 'experimentation',
 'stress testing',
 'graphic design',
 'motion design',
 'testing techniques',
 'software architecture',
 'java programming',
 'user feedback',
 'code reusability',
 'data governance',
 'animation',
 'typography',
 'scrum',
 'version control',
 'agile software development',
 'big data',
 'code coverage',
 'identity verification',
 'security assessment',
 'solid principles',
 'database management',
 'user personas',
 'lean startup',
 'security incident response plan',
 'stakeholder collaboration',
 'product owner',
 'social engineering',
 'product roadmap',
 'customer feedback',
 'cross-platform testing',
 'documentation',
 'product success',
 'security measures',
 'account security',
 'test automation tools',
 'information manipulation',
 'data processing',
 'content organization',
 'usability',
 'phishing attacks',
 'code quality',
 'information architecture',
 'data preprocessing',
 'device protection',
 'incident management',
 'emotional design',
 'testing changes',
 'git',
 'feature evaluation',
 'testing extremes',
 'automation',
 'role of a software architect',
 'security controls',
 'defect identification',
 'testing methods',
 'data-driven decision making',
 'agile practices',
 'build stability',
 'ci/cd',
 'testing efficiency',
 'test comprehensiveness',
 'product strategy',
 'compliance',
 'design principles',
 'scrum roles',
 'software development practices',
 'data dashboards',
 'performance testing',
 'api design',
 'load testing',
 'user acceptance testing',
 'user interfaces',
 'code maintainability',
 'technical writer',
 'data scientist',
 'agile manifesto',
 'software development lifecycle',
 'user testing',
 'scrum framework',
 'design tools',
 'data quality',
 'visual perception',
 'data protection',
 'testing processes',
 'nosql',
 'information security',
 'median',
 'ethical data use',
 'vulnerability management',
 'test engineer',
 'agile development',
 'network security',
 'product development',
 'responsible ai',
 'fail fast',
 'code review',
 'mobile app development',
 'vulnerability identification',
 'biometric authentication',
 'security analyst',
 'statistical analysis',
 'lean product development',
 'object-oriented design',
 'dry principle',
 'collaborative development',
 'software development',
 'data dictionary',
 'software testing',
 'web services',
 'visual communication',
 'continuous improvement',
 'authorization',
 'responsive design',
 'interactive design',
 'exploratory testing',
 'web design',
 'product manager',
 'iterative development',
 'usability testing',
 'agile principles',
 'color psychology',
 'testing phases',
 'compatibility testing',
 'user interface design',
 'iterative design',
 'environment compatibility',
 'cybersecurity threats',
 'devops',
 'testing existing functionality',
 'metadata',
 'black box testing',
 'collaboration',
 'interaction design',
 'continuous integration',
 'brand identity',
 'usability evaluation',
 'information hierarchy',
 'hardware',
 'ai foundations',
 'multimedia technologies',
 'logic design',
 'structured programming',
 'technology business',
 'coding',
 'operating systems',
 'software design',
 'electronics',
 'networking',
 'back-end',
 'leadership',
 'computer science',
 'advanced mathematics',
 'simulation',
 'formal languages',
 'thesis development',
 'application development',
 'algorithm design',
 'digital circuits',
 'research writing',
 'entrepreneurship',
 'management principles',
 'information organization',
 'network management',
 'programming',
 'research planning',
 'project management',
 'social issues',
 'language theory',
 'front-end',
 'technology integration',
 'language design',
 'presentation skills',
 'software engineering',
 'research methodology',
 'it support',
 'organizational management',
 'network protocols',
 'emerging technologies',
 'solution design',
 'databases',
 'integrative programming',
 'it infrastructure',
 'advanced information security',
 'algorithms',
 'artificial intelligence',
 'automata theory',
 'mathematics',
 'systems analysis',
 'programming languages',
 'quantitative analysis',
 'advanced software engineering',
 'optimization',
 'research methods',
 'administration',
 'design',
 'architecture design',
 'application design',
 'ethical decision-making',
 'system integration',
 'engineering',
 'complexity analysis',
 'network administration',
 'system architecture',
 'problem-solving',
 'system administration',
 'data structures',
 'it industry',
 'syntax',
 'interface design',
 'assembly language',
 'advanced programming',
 'web development',
 'maintenance',
 'computer architecture',
 'professional development',
 'data communication',
 'computing ethics',
 'multimedia content creation',
 'technical communication',
 'professional ethics',
 'modeling',
 'analysis']

In [24]:
# on mbti_skill_list, remove the skill that already exist in all__existing_skills
mbti_unique_skill_list = [skill for skill in mbti_skills_list if skill not in website_skill_list]
mbti_unique_skill_list

['strategic planning',
 ' critical thinking',
 ' data analysis',
 ' problem solving',
 ' decision making',
 ' management',
 ' strategic thinking',
 'research',
 ' creative problem solving',
 ' logic',
 ' scientific inquiry',
 'idea generation',
 ' innovation',
 ' adaptability',
 ' problem solving',
 'counseling',
 ' empathy',
 ' active listening',
 ' emotional intelligence',
 ' relationship building',
 ' mentorship',
 ' empathy',
 'creative writing',
 ' artistic expression',
 ' advocacy',
 ' empathy',
 'creative brainstorming',
 ' public speaking',
 ' entrepreneurship',
 ' adaptability',
 ' data analysis',
 ' organization',
 ' reliability',
 ' time management',
 ' process improvement',
 ' decision making',
 'caregiving',
 ' active listening',
 ' attention to detail',
 ' empathy',
 'social organizing',
 ' event planning',
 ' community building',
 ' empathy',
 'troubleshooting',
 ' mechanical skills',
 ' outdoor activities',
 ' problem solving',
 'risk taking',
 ' physical activities',
 ' spontaneous decision making',
 ' adaptability',
 'artistic expression',
 ' emotional expression',
 ' individualism',
 ' creativity',
 'entertaining',
 ' social interactions',
 ' adaptability',
 ' spontaneity']

In [25]:
print(len(mbti_unique_skill_list))

60

In [26]:
# # convert the list of unique skills to a DataFrame
skills_df = pd.DataFrame(mbti_unique_skill_list, columns=['skill'])
skills_df.head()

                skill
0  strategic planning
1   critical thinking
2       data analysis
3     problem solving
4     decision making

In [27]:
# get last id of skill
last_id = website_skill['id'].max()
last_id

316

In [28]:
# add id to skills_df
skills_df['id'] = skills_df.index + last_id + 1
# reorder
skills_df = skills_df[['id', 'skill']]
skills_df.head()

    id               skill
0  317  strategic planning
1  318   critical thinking
2  319       data analysis
3  320     problem solving
4  321     decision making

In [29]:
website_skill.tail(3)

      id                skill
313  314  professional ethics
314  315             modeling
315  316             analysis

In [30]:
# combine skills_df and website_skill
website_skill = pd.concat([website_skill, skills_df])
website_skill.tail()

     id                 skill
55  372            creativity
56  373          entertaining
57  374   social interactions
58  375          adaptability
59  376           spontaneity

In [32]:
# reset index
website_skill.reset_index(drop=True, inplace=True)
website_skill.tail()

      id                 skill
371  372            creativity
372  373          entertaining
373  374   social interactions
374  375          adaptability
375  376           spontaneity

In [33]:
# save to csv
website_skill.to_csv('../../static/csv/skill_3.csv', index=False)

# MBTI Skill Mapping

In [8]:
import numpy as np
import pandas as pd
import ast

In [2]:
# load skill_3.csv
website_skill = pd.read_csv('../../static/csv/skill_3.csv')
website_skill.head(3)

   id                            skill
0   1                quality assurance
1   2  software development principles
2   3  software development life cycle

In [6]:
# load mbti_skills.csv
mbti_skills = pd.read_csv('../../static/csv/mbti_skills.csv')
mbti_skills.head(3)

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"['strategic planning', ' critical thinking', '..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","['leadership', ' decision making', ' managemen..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","['research', ' creative problem solving', ' lo..."

# sjhfalsshad

In [9]:
# use ast to convert string to list
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: ast.literal_eval(x))

In [10]:
# convert skill_list to mbti_skill_list
mbti_skill_list = []
for i in mbti_skills['skill_list']:
    mbti_skill_list += i

mbti_skill_list

['strategic planning',
 ' critical thinking',
 ' data analysis',
 ' problem solving',
 'leadership',
 ' decision making',
 ' management',
 ' strategic thinking',
 'research',
 ' creative problem solving',
 ' logic',
 ' scientific inquiry',
 'idea generation',
 ' innovation',
 ' adaptability',
 ' problem solving',
 'counseling',
 ' empathy',
 ' active listening',
 ' emotional intelligence',
 'leadership',
 ' relationship building',
 ' mentorship',
 ' empathy',
 'creative writing',
 ' artistic expression',
 ' advocacy',
 ' empathy',
 'creative brainstorming',
 ' public speaking',
 ' entrepreneurship',
 ' adaptability',
 'project management',
 ' data analysis',
 ' organization',
 ' reliability',
 'leadership',
 ' time management',
 ' process improvement',
 ' decision making',
 'caregiving',
 ' active listening',
 ' attention to detail',
 ' empathy',
 'social organizing',
 ' event planning',
 ' community building',
 ' empathy',
 'troubleshooting',
 ' mechanical skills',
 ' outdoor activities',
 ' problem solving',
 'risk taking',
 ' physical activities',
 ' spontaneous decision making',
 ' adaptability',
 'artistic expression',
 ' emotional expression',
 ' individualism',
 ' creativity',
 'entertaining',
 ' social interactions',
 ' adaptability',
 ' spontaneity']

In [11]:
# strip space at front and back of skill
mbti_skill_list = [skill.strip() for skill in mbti_skill_list]
mbti_skill_list

['strategic planning',
 'critical thinking',
 'data analysis',
 'problem solving',
 'leadership',
 'decision making',
 'management',
 'strategic thinking',
 'research',
 'creative problem solving',
 'logic',
 'scientific inquiry',
 'idea generation',
 'innovation',
 'adaptability',
 'problem solving',
 'counseling',
 'empathy',
 'active listening',
 'emotional intelligence',
 'leadership',
 'relationship building',
 'mentorship',
 'empathy',
 'creative writing',
 'artistic expression',
 'advocacy',
 'empathy',
 'creative brainstorming',
 'public speaking',
 'entrepreneurship',
 'adaptability',
 'project management',
 'data analysis',
 'organization',
 'reliability',
 'leadership',
 'time management',
 'process improvement',
 'decision making',
 'caregiving',
 'active listening',
 'attention to detail',
 'empathy',
 'social organizing',
 'event planning',
 'community building',
 'empathy',
 'troubleshooting',
 'mechanical skills',
 'outdoor activities',
 'problem solving',
 'risk taking',
 'physical activities',
 'spontaneous decision making',
 'adaptability',
 'artistic expression',
 'emotional expression',
 'individualism',
 'creativity',
 'entertaining',
 'social interactions',
 'adaptability',
 'spontaneity']

# sjhfalsshad

In [13]:
# convert website_skill to dictionary
# skill_mapping = unique_skills_df.set_index('skill')['id'].to_dict()
website_skill_dict = website_skill.set_index('skill')['id'].to_dict()

In [14]:
# create dictionary of skill and id
website_skill_dict

{'quality assurance': 1,
 'software development principles': 2,
 'software development life cycle': 3,
 'agile methodology': 4,
 'innovation': 329,
 'fail cheap': 6,
 'authentication methods': 7,
 'adaptability in development': 8,
 'inclusive design': 9,
 'product launch': 10,
 'svn': 11,
 'learning culture': 12,
 'ux design': 13,
 'ui/ux design software': 14,
 'software quality assurance': 15,
 'security incident handling': 16,
 'exploratory data analysis': 17,
 'source code management': 18,
 'risk-taking': 19,
 'knowledge transfer': 20,
 'mvp': 21,
 'regression testing': 22,
 'information security compliance': 23,
 'data analytics': 24,
 'statistics': 25,
 'prototyping': 26,
 'color theory': 27,
 'product goals': 28,
 'user-centered design': 29,
 'product management': 30,
 'lean thinking': 31,
 'product documentation': 32,
 'data security': 33,
 'software development process': 34,
 'product backlog': 35,
 'privacy': 36,
 'complementary colors': 37,
 'identity management': 38,
 'security policy': 39,
 'empathy in design': 40,
 'automated testing': 41,
 'feature prioritization': 42,
 'pattern recognition': 43,
 'product planning': 44,
 'wireframing': 45,
 'usability principles': 46,
 'design guidelines': 47,
 'data cleaning': 48,
 'organizational security': 49,
 'design process': 50,
 'tableau': 51,
 'unit testing': 52,
 'sql': 53,
 'cybersecurity': 54,
 'two-factor authentication': 55,
 'design ethics': 56,
 'security principles': 57,
 'data visualization': 58,
 'penetration testing': 59,
 'feature engineering': 60,
 'user verification': 61,
 'scrum master': 62,
 'model performance': 63,
 'consistency in design': 64,
 'database querying': 65,
 'color schemes': 66,
 'user experience testing': 67,
 'restful api': 68,
 'performance evaluation': 69,
 'data management': 70,
 'a/b testing': 71,
 'user experience': 72,
 'android development': 73,
 'user interface': 74,
 'accessibility': 75,
 'data science': 76,
 'smoke testing': 77,
 'data ethics': 78,
 'mobile responsiveness': 79,
 'machine learning': 80,
 'predictive modeling': 81,
 'ui/ux design': 82,
 'endpoint security': 83,
 'data analysis': 347,
 'acceptance criteria': 85,
 'testing metrics': 86,
 'api': 87,
 'defect detection': 88,
 'access control': 89,
 'user experience optimization': 90,
 'threat mitigation': 91,
 'user navigation': 92,
 'authentication': 93,
 'software integration': 94,
 'experimentation': 95,
 'stress testing': 96,
 'graphic design': 97,
 'motion design': 98,
 'testing techniques': 99,
 'software architecture': 100,
 'java programming': 101,
 'user feedback': 102,
 'code reusability': 103,
 'data governance': 104,
 'animation': 105,
 'typography': 106,
 'scrum': 107,
 'version control': 108,
 'agile software development': 109,
 'big data': 110,
 'code coverage': 111,
 'identity verification': 112,
 'security assessment': 113,
 'solid principles': 114,
 'database management': 115,
 'user personas': 116,
 'lean startup': 117,
 'security incident response plan': 118,
 'stakeholder collaboration': 119,
 'product owner': 120,
 'social engineering': 121,
 'product roadmap': 122,
 'customer feedback': 123,
 'cross-platform testing': 124,
 'documentation': 125,
 'product success': 126,
 'security measures': 127,
 'account security': 128,
 'test automation tools': 129,
 'information manipulation': 130,
 'data processing': 131,
 'content organization': 132,
 'usability': 133,
 'phishing attacks': 134,
 'code quality': 135,
 'information architecture': 136,
 'data preprocessing': 137,
 'device protection': 138,
 'incident management': 139,
 'emotional design': 140,
 'testing changes': 141,
 'git': 142,
 'feature evaluation': 143,
 'testing extremes': 144,
 'automation': 145,
 'role of a software architect': 146,
 'security controls': 147,
 'defect identification': 148,
 'testing methods': 149,
 'data-driven decision making': 150,
 'agile practices': 151,
 'build stability': 152,
 'ci/cd': 153,
 'testing efficiency': 154,
 'test comprehensiveness': 155,
 'product strategy': 156,
 'compliance': 157,
 'design principles': 158,
 'scrum roles': 159,
 'software development practices': 160,
 'data dashboards': 161,
 'performance testing': 162,
 'api design': 163,
 'load testing': 164,
 'user acceptance testing': 165,
 'user interfaces': 166,
 'code maintainability': 167,
 'technical writer': 168,
 'data scientist': 169,
 'agile manifesto': 170,
 'software development lifecycle': 171,
 'user testing': 172,
 'scrum framework': 173,
 'design tools': 174,
 'data quality': 175,
 'visual perception': 176,
 'data protection': 177,
 'testing processes': 178,
 'nosql': 179,
 'information security': 180,
 'median': 181,
 'ethical data use': 182,
 'vulnerability management': 183,
 'test engineer': 184,
 'agile development': 185,
 'network security': 186,
 'product development': 187,
 'responsible ai': 188,
 'fail fast': 189,
 'code review': 190,
 'mobile app development': 191,
 'vulnerability identification': 192,
 'biometric authentication': 193,
 'security analyst': 194,
 'statistical analysis': 195,
 'lean product development': 196,
 'object-oriented design': 197,
 'dry principle': 198,
 'collaborative development': 199,
 'software development': 200,
 'data dictionary': 201,
 'software testing': 202,
 'web services': 203,
 'visual communication': 204,
 'continuous improvement': 205,
 'authorization': 206,
 'responsive design': 207,
 'interactive design': 208,
 'exploratory testing': 209,
 'web design': 210,
 'product manager': 211,
 'iterative development': 212,
 'usability testing': 213,
 'agile principles': 214,
 'color psychology': 215,
 'testing phases': 216,
 'compatibility testing': 217,
 'user interface design': 218,
 'iterative design': 219,
 'environment compatibility': 220,
 'cybersecurity threats': 221,
 'devops': 222,
 'testing existing functionality': 223,
 'metadata': 224,
 'black box testing': 225,
 'collaboration': 226,
 'interaction design': 227,
 'continuous integration': 228,
 'brand identity': 229,
 'usability evaluation': 230,
 'information hierarchy': 231,
 'hardware': 232,
 'ai foundations': 233,
 'multimedia technologies': 234,
 'logic design': 235,
 'structured programming': 236,
 'technology business': 237,
 'coding': 238,
 'operating systems': 239,
 'software design': 240,
 'electronics': 241,
 'networking': 242,
 'back-end': 243,
 'leadership': 244,
 'computer science': 245,
 'advanced mathematics': 246,
 'simulation': 247,
 'formal languages': 248,
 'thesis development': 249,
 'application development': 250,
 'algorithm design': 251,
 'digital circuits': 252,
 'research writing': 253,
 'entrepreneurship': 345,
 'management principles': 255,
 'information organization': 256,
 'network management': 257,
 'programming': 258,
 'research planning': 259,
 'project management': 260,
 'social issues': 261,
 'language theory': 262,
 'front-end': 263,
 'technology integration': 264,
 'language design': 265,
 'presentation skills': 266,
 'software engineering': 267,
 'research methodology': 268,
 'it support': 269,
 'organizational management': 270,
 'network protocols': 271,
 'emerging technologies': 272,
 'solution design': 273,
 'databases': 274,
 'integrative programming': 275,
 'it infrastructure': 276,
 'advanced information security': 277,
 'algorithms': 278,
 'artificial intelligence': 279,
 'automata theory': 280,
 'mathematics': 281,
 'systems analysis': 282,
 'programming languages': 283,
 'quantitative analysis': 284,
 'advanced software engineering': 285,
 'optimization': 286,
 'research methods': 287,
 'administration': 288,
 'design': 289,
 'architecture design': 290,
 'application design': 291,
 'ethical decision-making': 292,
 'system integration': 293,
 'engineering': 294,
 'complexity analysis': 295,
 'network administration': 296,
 'system architecture': 297,
 'problem-solving': 298,
 'system administration': 299,
 'data structures': 300,
 'it industry': 301,
 'syntax': 302,
 'interface design': 303,
 'assembly language': 304,
 'advanced programming': 305,
 'web development': 306,
 'maintenance': 307,
 'computer architecture': 308,
 'professional development': 309,
 'data communication': 310,
 'computing ethics': 311,
 'multimedia content creation': 312,
 'technical communication': 313,
 'professional ethics': 314,
 'modeling': 315,
 'analysis': 316,
 'strategic planning': 317,
 'critical thinking': 318,
 'problem solving': 364,
 'decision making': 352,
 'management': 322,
 'strategic thinking': 323,
 'research': 324,
 'creative problem solving': 325,
 'logic': 326,
 'scientific inquiry': 327,
 'idea generation': 328,
 'adaptability': 375,
 'counseling': 332,
 'empathy': 360,
 'active listening': 354,
 'emotional intelligence': 335,
 'relationship building': 336,
 'mentorship': 337,
 'creative writing': 339,
 'artistic expression': 369,
 'advocacy': 341,
 'creative brainstorming': 343,
 'public speaking': 344,
 'organization': 348,
 'reliability': 349,
 'time management': 350,
 'process improvement': 351,
 'caregiving': 353,
 'attention to detail': 355,
 'social organizing': 357,
 'event planning': 358,
 'community building': 359,
 'troubleshooting': 361,
 'mechanical skills': 362,
 'outdoor activities': 363,
 'risk taking': 365,
 'physical activities': 366,
 'spontaneous decision making': 367,
 'emotional expression': 370,
 'individualism': 371,
 'creativity': 372,
 'entertaining': 373,
 'social interactions': 374,
 'spontaneity': 376}

In [17]:
mbti_skills.head(3)

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"[strategic planning, critical thinking, data..."
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","[leadership, decision making, management, s..."
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","[research, creative problem solving, logic, ..."

In [18]:
# strip space at front and back of skill
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [skill.strip() for skill in x])

In [19]:
# apply skill_mapping to skill_list
mbti_skills['skill_list'] = mbti_skills['skill_list'].apply(lambda x: [website_skill_dict[i] for i in x])
mbti_skills.head()

,id,mbti,mbti_name,description,skill_list
0,1,INTJ,Architect,INTJs are visionaries. They are analytical pro...,"[317, 318, 347, 364]"
1,2,ENTJ,Commander,"ENTJs are natural leaders. They are assertive,...","[244, 352, 322, 323]"
2,3,INTP,Logician,"INTPs are creative thinkers. They are curious,...","[324, 325, 326, 327]"
3,4,ENTP,Debater,ENTPs are enthusiastic innovators. They are ad...,"[328, 329, 375, 364]"
4,5,INFJ,Advocate,INFJs are empathetic counselors. They are comp...,"[332, 360, 354, 335]"

In [20]:
# explode
mbti_skills = mbti_skills.explode('skill_list')
# get id, and skill_list
mbti_skills = mbti_skills[['id', 'skill_list']]
mbti_skills.head()

   id skill_list
0   1        317
0   1        318
0   1        347
0   1        364
1   2        244

In [28]:
# rename column
mbti_skills.rename(columns={'skill_list': 'skill_id', 'mbti_id':'indicator_id'}, inplace=True)
mbti_skills.sample(2)

    id  indicator_id skill_id
20  21             6      244
45  46            12      358

In [24]:
# reset index
mbti_skills.reset_index(drop=True, inplace=True)

In [25]:
# add id
mbti_skills['id'] = mbti_skills.index + 1
mbti_skills.head(3)

   mbti_id skill_id  id
0        1      317   1
1        1      318   2
2        1      347   3

In [26]:
mbti_skills.tail(3)

    mbti_id skill_id  id
61       16      374  62
62       16      375  63
63       16      376  64

In [29]:
# reoder column
#mbti_skills = mbti_skills[['id', 'mbti_id', 'skill_id']]
mbti_skills.head(3)

   id  indicator_id skill_id
0   1             1      317
1   2             1      318
2   3             1      347

In [30]:
# save to csv
mbti_skills.to_csv('../../static/csv/personality_indicator_skills.csv', index=False)