In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
df = pd.read_csv('../../static/csv/test_5.csv')
df.head()

,question_id,question,description,options,skills_list,correct_option,field_id
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"[""To track changes in code"", ""To format text"",...","['Version Control','Source Code Management','C...",0,1
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"[""Don""t Repeat Yourself"", ""Design Reusable Yie...","[""Software Development Principles"",""DRY Princi...",0,1
2,3,Which programming language is known for its us...,Identify the programming language commonly ass...,"[""Java"", ""Python"", ""Ruby"", ""C++""]","[""Android Development"",""Java Programming"",""Mob...",0,1
3,4,"What does the term ""API"" stand for in software...",Select one option you think is right.,"[""Application Programming Interface"",""Advanced...","[""API"",""Software Integration"",""Web Services"",""...",0,1
4,5,What is the primary purpose of unit testing in...,Select the main objective of unit testing.,"[""To test individual components or functions"",...","[""Unit Testing"",""Software Testing"",""Code Quali...",0,1

In [3]:
# Convert the string representation of lists into actual lists
df['skills_list'] = df['skills_list'].apply(ast.literal_eval)
df.head()

,question_id,question,description,options,skills_list,correct_option,field_id
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"[""To track changes in code"", ""To format text"",...","[Version Control, Source Code Management, Coll...",0,1
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"[""Don""t Repeat Yourself"", ""Design Reusable Yie...","[Software Development Principles, DRY Principl...",0,1
2,3,Which programming language is known for its us...,Identify the programming language commonly ass...,"[""Java"", ""Python"", ""Ruby"", ""C++""]","[Android Development, Java Programming, Mobile...",0,1
3,4,"What does the term ""API"" stand for in software...",Select one option you think is right.,"[""Application Programming Interface"",""Advanced...","[API, Software Integration, Web Services, appl...",0,1
4,5,What is the primary purpose of unit testing in...,Select the main objective of unit testing.,"[""To test individual components or functions"",...","[Unit Testing, Software Testing, Code Quality,...",0,1

In [5]:
# to lower case
df['skills_list'] = df['skills_list'].apply(lambda x: [y.lower() for y in x])
df.head()

,question_id,question,description,options,skills_list,correct_option,field_id
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"[""To track changes in code"", ""To format text"",...","[version control, source code management, coll...",0,1
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"[""Don""t Repeat Yourself"", ""Design Reusable Yie...","[software development principles, dry principl...",0,1
2,3,Which programming language is known for its us...,Identify the programming language commonly ass...,"[""Java"", ""Python"", ""Ruby"", ""C++""]","[android development, java programming, mobile...",0,1
3,4,"What does the term ""API"" stand for in software...",Select one option you think is right.,"[""Application Programming Interface"",""Advanced...","[api, software integration, web services, appl...",0,1
4,5,What is the primary purpose of unit testing in...,Select the main objective of unit testing.,"[""To test individual components or functions"",...","[unit testing, software testing, code quality,...",0,1

In [5]:
# # save to csv
df.to_csv('../../static/csv/test_3.csv', index=False)

In [6]:
# replace '-' with ' '
df['skills_list'] = df['skills_list'].apply(lambda x: [y.replace('-', ' ') for y in x])

In [7]:
# remove strings 'skills' and 'skill'
df['skills_list'] = df['skills_list'].apply(lambda x: [y.replace('skills', '') for y in x])

In [8]:
# Create a list of skills by combining all the skills from the 'skills_list' column
all_skills = [skill for skills_list in df['skills_list'] for skill in skills_list]

# Now, 'all_skills' contains all the skills from the DataFrame
print(all_skills)

['version control', 'source code management', 'collaborative development', 'vcs', 'software development principles', 'dry principle', 'code reusability', 'dry', 'principles', 'android development', 'java programming', 'mobile app development', 'android', 'app', 'java', 'programming', 'mobile', 'development', 'api', 'software integration', 'web services', 'application programming interface', 'unit testing', 'software testing', 'code quality', 'testing', 'unit', 'test', 'quality', 'data cleaning', 'data preprocessing', 'data analysis', 'cleaning', 'processing', 'data', 'data science', 'data analytics', 'data visualization', 'data analytics', 'data dashboards', 'tableau', 'dashboards', 'dashboard', 'visualization', 'analytics', 'data visualization', 'data analytics', 'data dashboards', 'tableau', 'patterns', 'pattern recognition', 'insights', 'data', 'analytics', 'visualization', 'dashboard', 'sql', 'database querying', 'database management', 'database', 'db', 'mysql', 'structured query language', 'statistics', 'median', 'data analysis', 'analytics', 'statistics', 'math', 'design principles', 'consistency in design', 'user interface design', 'interface', 'user', 'design', 'visual design', 'design principles', 'consistency,gestalt principles', 'color theory', 'complementary colors', 'color schemes', 'color', 'design', 'elements', 'user testing', 'user experience testing', 'usability evaluation', 'design tools', 'wireframing', 'prototyping', 'ui/ux design software', 'product management', 'product manager', 'feature prioritization', 'product roadmap', 'product planning', 'product strategy', 'agile methodology', 'iterative development', 'customer feedback', 'scrum', 'product strategy', 'product documentation', 'product goals', 'mvp', 'product development', 'product launch', 'software testing', 'quality assurance', 'defect detection', 'regression testing', 'software testing', 'testing changes', 'load testing', 'software testing', 'performance testing', 'software testing', 'penetration testing', 'vulnerability assessment', 'testing', 'penetration', 'vulnerability', 'assessment', 'usability testing', 'user experience testing', 'user centered design', 'data security', 'encryption', 'data masking', 'masking', 'security', 'cybersecurity', 'social engineering', 'spear phishing', 'identity verification', 'authentication', 'authorization', 'multi factor authentication', 'network security', 'firewall', 'network perimeter protection', 'security', 'network', 'protection', 'access control', 'security principles', 'authorization', 'access control', 'least privilege,principle of least privilege', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'code review', 'software development', 'collaborative development', 'continuous integration', 'ci/cd', 'software development practices', 'software architecture', 'software development', 'role of a software architect', 'devops', 'collaboration', 'continuous integration', 'software development practices', 'restful api', 'web services', 'api design', 'software development', 'agile software development', 'agile manifesto', 'scrum', 'software development principles', 'scrum framework', 'product owner', 'agile development', 'scrum roles', 'solid principles', 'object oriented design', 'software architecture', 'code maintainability', 'exploratory data analysis', 'data science', 'data analysis', 'statistical analysis', 'data preprocessing', 'machine learning', 'feature engineering', 'model performance', 'data dictionary', 'database management', 'metadata', 'data governance', 'big data', 'data processing', 'data analytics', 'nosql', 'data scientist', 'data analysis', 'predictive modeling', 'data driven decision making', 'data governance', 'data management', 'data quality', 'compliance', 'machine learning', 'data analysis', 'predictive modeling', 'pattern recognition', 'a/b testing', 'experimentation', 'data driven decision making', 'statistical analysis', 'data ethics', 'ethical data use', 'privacy', 'responsible ai', 'data security', 'data management', 'information security', 'cybersecurity', 'typography', 'graphic design', 'visual communication', 'brand identity', 'responsive design', 'user experience', 'web design', 'mobile responsiveness', 'information architecture', 'web design', 'user navigation', 'content organization', 'color psychology', 'design principles', 'emotional design', 'visual perception', 'motion design', 'user interfaces', 'interactive design', 'animation', 'user personas', 'user centered design', 'ux design', 'empathy in design', 'accessibility', 'inclusive design', 'usability', 'design ethics', 'prototyping', 'design process', 'user testing', 'iterative design', 'wireframing', 'ui/ux design', 'user interface', 'information hierarchy', 'interaction design', 'user interface design', 'usability principles', 'design guidelines', 'scrum framework', 'agile development', 'scrum master', 'agile practices', 'iterative development', 'product success', 'agile principles', 'adaptability in development', 'product owner', 'agile development', 'product backlog', 'stakeholder collaboration', 'user feedback', 'product development', 'usability testing', 'iterative design', 'lean product development', 'lean thinking', 'agile principles', 'continuous improvement', 'mvp', 'product development', 'product launch', 'lean startup', 'fail fast', 'fail cheap', 'innovation', 'risk taking', 'learning culture', 'technical writer', 'documentation', 'software development process', 'knowledge transfer', 'devops', 'software development lifecycle', 'continuous integration', 'automation', 'a/b testing', 'product development', 'user experience optimization', 'feature evaluation', 'two factor authentication', 'account security', 'authentication methods', 'security analyst', 'cybersecurity', 'information security', 'security measures', 'endpoint security', 'security', 'network security', 'device protection', 'social engineering', 'cybersecurity threats', 'information manipulation', 'phishing attacks', 'security policy', 'organizational security', 'information security compliance', 'security measures', 'penetration testing', 'cybersecurity', 'security assessment', 'vulnerability identification', 'information security', 'security principles', 'data protection', 'security controls', 'biometric authentication', 'user verification', 'cybersecurity', 'identity management', 'vulnerability management', 'security', 'security assessment', 'threat mitigation', 'security incident response plan', 'incident management', 'security incident handling', 'security', 'incident', 'user acceptance testing', 'software testing', 'quality assurance', 'acceptance criteria', 'test engineer', 'software testing', 'quality assurance', 'testing processes', 'exploratory testing', 'software testing', 'defect identification', 'testing methods', 'stress testing', 'software quality assurance', 'performance evaluation', 'testing extremes', 'smoke testing', 'software testing', 'build stability', 'testing phases', 'black box testing', 'software quality assurance', 'defect identification', 'testing techniques', 'regression testing', 'software development life cycle', 'quality assurance', 'testing existing functionality', 'automated testing', 'software quality assurance', 'testing efficiency', 'test automation tools', 'code coverage', 'software testing', 'testing metrics', 'test comprehensiveness', 'compatibility testing', 'software quality assurance', 'cross platform testing', 'environment compatibility']

In [9]:
len(all_skills)

393

In [10]:
# remove duplicates
all_skills = list(set(all_skills))

In [11]:
# sample skills from all_skills
sample = np.random.choice(all_skills, 10)
print(sample)

['user testing' 'compatibility testing' 'build stability'
 'security incident handling' 'data cleaning' 'user feedback'
 'security controls' 'privacy' 'data ethics' 'ui/ux design']

In [12]:
# get unique skills
unique_skills = list(set(all_skills))
print(unique_skills)
# count the number of unique skills
print(len(unique_skills))

['regression testing', 'android', 'statistics', 'scrum framework', 'test', 'security principles', 'big data', 'lean startup', 'svn', 'math', 'product success', 'motion design', 'compatibility testing', 'security incident handling', 'lean product development', 'usability testing', 'product management', 'database', 'object oriented design', 'typography', 'web design', 'animation', 'responsible ai', 'machine learning', 'quality', 'penetration testing', 'software architecture', 'prototyping', 'product launch', 'continuous integration', 'database management', 'penetration', 'security controls', 'predictive modeling', 'db', 'black box testing', 'programming', 'firewall', 'privacy', 'identity verification', 'data masking', 'solid principles', 'design principles', 'agile practices', 'ux design', 'software development life cycle', 'dashboards', 'code review', 'performance testing', 'software testing', 'software development process', 'testing', 'pattern recognition', 'product backlog', 'collaboration', 'performance evaluation', 'mobile', 'automated testing', 'user acceptance testing', 'innovation', 'cybersecurity threats', 'design guidelines', 'testing techniques', 'test automation tools', 'software development principles', 'color theory', 'dry', 'product documentation', 'app', 'phishing attacks', 'feature prioritization', 'environment compatibility', 'device protection', 'code coverage', 'security measures', 'inclusive design', 'brand identity', 'assessment', 'agile development', 'experimentation', 'visual communication', 'empathy in design', 'vcs', 'emotional design', 'restful api', 'scrum master', 'iterative development', 'testing methods', 'security incident response plan', 'network security', 'risk taking', 'identity management', 'smoke testing', 'quality assurance', 'wireframing', 'product planning', 'vulnerability identification', 'user testing', 'unit', 'incident', 'insights', 'design tools', 'lean thinking', 'consistency in design', 'user experience', 'fail fast', 'product manager', 'color', 'data dictionary', 'incident management', 'mvp', 'user interface', 'exploratory testing', 'security policy', 'threat mitigation', 'authentication methods', 'network', 'git', 'biometric authentication', 'product roadmap', 'devops', 'masking', 'user interfaces', 'accessibility', 'java programming', 'content organization', 'sql', 'feature engineering', 'product development', 'version control', 'information manipulation', 'testing existing functionality', 'data management', 'user experience testing', 'usability', 'tableau', 'agile principles', 'agile methodology', 'protection', 'analytics', 'product goals', 'user personas', 'ui/ux design', 'adaptability in development', 'endpoint security', 'role of a software architect', 'network perimeter protection', 'user', 'product strategy', 'ethical data use', 'distributed version control', 'test engineer', 'interface', 'color psychology', 'testing phases', 'collaborative development', 'patterns', 'continuous improvement', 'api', 'data preprocessing', 'unit testing', 'data governance', 'security', 'data scientist', 'interactive design', 'automation', 'stress testing', 'visualization', 'defect detection', 'iterative design', 'data science', 'source code management', 'usability principles', 'security assessment', 'api design', 'product owner', 'ui/ux design software', 'software development practices', 'design ethics', 'information architecture', 'data security', 'authentication', 'user verification', 'authorization', 'scrum', 'cleaning', 'test comprehensiveness', 'scrum roles', 'design', 'social engineering', 'agile manifesto', 'testing efficiency', 'two factor authentication', 'nosql', 'user centered design', 'data driven decision making', 'agile software development', 'software development lifecycle', 'data dashboards', 'access control', 'stakeholder collaboration', 'processing', 'mobile app development', 'responsive design', 'feature evaluation', 'testing changes', 'software integration', 'dry principle', 'visual perception', 'acceptance criteria', 'documentation', 'security analyst', 'statistical analysis', 'account security', 'web services', 'vulnerability assessment', 'structured query language', 'development', 'data analytics', 'visual design', 'software development', 'vulnerability management', 'dashboard', 'complementary colors', 'least privilege,principle of least privilege', 'exploratory data analysis', 'cybersecurity', 'application programming interface', 'data', 'testing processes', 'user interface design', 'code reusability', 'multi factor authentication', 'user feedback', 'design process', 'learning culture', 'information hierarchy', 'technical writer', 'build stability', 'compliance', 'model performance', 'cross platform testing', 'user navigation', 'data cleaning', 'data ethics', 'data protection', 'graphic design', 'database querying', 'information security compliance', 'data processing', 'principles', 'a/b testing', 'information security', 'defect identification', 'consistency,gestalt principles', 'vulnerability', 'data quality', 'color schemes', 'ci/cd', 'software quality assurance', 'git workflow', 'fail cheap', 'median', 'code quality', 'knowledge transfer', 'organizational security', 'elements', 'spear phishing', 'testing extremes', 'centralized version control', 'java', 'interaction design', 'user experience optimization', 'data analysis', 'testing metrics', 'code maintainability', 'encryption', 'usability evaluation', 'customer feedback', 'android development', 'mysql', 'mobile responsiveness', 'metadata', 'load testing', 'data visualization']
285

In [14]:
# make it a dataframe
unique_skills_df = pd.DataFrame(unique_skills, columns=['skill'])
# add id column, starting from 1
unique_skills_df['id'] = np.arange(len(unique_skills_df)) + 1
# reorder columns
unique_skills_df = unique_skills_df[['id', 'skill']]
unique_skills_df

      id                  skill
0      1     regression testing
1      2                android
2      3             statistics
3      4        scrum framework
4      5                   test
..   ...                    ...
280  281                  mysql
281  282  mobile responsiveness
282  283               metadata
283  284           load testing
284  285     data visualization

[285 rows x 2 columns]

In [15]:
# save to csv
unique_skills_df.to_csv('../../static/csv/skill_1.csv', index=False)

In [16]:
# load the csv file
unique_skills_df = pd.read_csv('../../static/csv/skill_1.csv')

In [17]:
skill_mapping = unique_skills_df.set_index('skill')['id'].to_dict()

In [18]:
skill_mapping

{'regression testing': 1,
 'android': 2,
 'statistics': 3,
 'scrum framework': 4,
 'test': 5,
 'security principles': 6,
 'big data': 7,
 'lean startup': 8,
 'svn': 9,
 'math': 10,
 'product success': 11,
 'motion design': 12,
 'compatibility testing': 13,
 'security incident handling': 14,
 'lean product development': 15,
 'usability testing': 16,
 'product management': 17,
 'database': 18,
 'object oriented design': 19,
 'typography': 20,
 'web design': 21,
 'animation': 22,
 'responsible ai': 23,
 'machine learning': 24,
 'quality': 25,
 'penetration testing': 26,
 'software architecture': 27,
 'prototyping': 28,
 'product launch': 29,
 'continuous integration': 30,
 'database management': 31,
 'penetration': 32,
 'security controls': 33,
 'predictive modeling': 34,
 'db': 35,
 'black box testing': 36,
 'programming': 37,
 'firewall': 38,
 'privacy': 39,
 'identity verification': 40,
 'data masking': 41,
 'solid principles': 42,
 'design principles': 43,
 'agile practices': 44,
 'ux design': 45,
 'software development life cycle': 46,
 'dashboards': 47,
 'code review': 48,
 'performance testing': 49,
 'software testing': 50,
 'software development process': 51,
 'testing': 52,
 'pattern recognition': 53,
 'product backlog': 54,
 'collaboration': 55,
 'performance evaluation': 56,
 'mobile': 57,
 'automated testing': 58,
 'user acceptance testing': 59,
 'innovation': 60,
 'cybersecurity threats': 61,
 'design guidelines': 62,
 'testing techniques': 63,
 'test automation tools': 64,
 'software development principles': 65,
 'color theory': 66,
 'dry': 67,
 'product documentation': 68,
 'app': 69,
 'phishing attacks': 70,
 'feature prioritization': 71,
 'environment compatibility': 72,
 'device protection': 73,
 'code coverage': 74,
 'security measures': 75,
 'inclusive design': 76,
 'brand identity': 77,
 'assessment': 78,
 'agile development': 79,
 'experimentation': 80,
 'visual communication': 81,
 'empathy in design': 82,
 'vcs': 83,
 'emotional design': 84,
 'restful api': 85,
 'scrum master': 86,
 'iterative development': 87,
 'testing methods': 88,
 'security incident response plan': 89,
 'network security': 90,
 'risk taking': 91,
 'identity management': 92,
 'smoke testing': 93,
 'quality assurance': 94,
 'wireframing': 95,
 'product planning': 96,
 'vulnerability identification': 97,
 'user testing': 98,
 'unit': 99,
 'incident': 100,
 'insights': 101,
 'design tools': 102,
 'lean thinking': 103,
 'consistency in design': 104,
 'user experience': 105,
 'fail fast': 106,
 'product manager': 107,
 'color': 108,
 'data dictionary': 109,
 'incident management': 110,
 'mvp': 111,
 'user interface': 112,
 'exploratory testing': 113,
 'security policy': 114,
 'threat mitigation': 115,
 'authentication methods': 116,
 'network': 117,
 'git': 118,
 'biometric authentication': 119,
 'product roadmap': 120,
 'devops': 121,
 'masking': 122,
 'user interfaces': 123,
 'accessibility': 124,
 'java programming': 125,
 'content organization': 126,
 'sql': 127,
 'feature engineering': 128,
 'product development': 129,
 'version control': 130,
 'information manipulation': 131,
 'testing existing functionality': 132,
 'data management': 133,
 'user experience testing': 134,
 'usability': 135,
 'tableau': 136,
 'agile principles': 137,
 'agile methodology': 138,
 'protection': 139,
 'analytics': 140,
 'product goals': 141,
 'user personas': 142,
 'ui/ux design': 143,
 'adaptability in development': 144,
 'endpoint security': 145,
 'role of a software architect': 146,
 'network perimeter protection': 147,
 'user': 148,
 'product strategy': 149,
 'ethical data use': 150,
 'distributed version control': 151,
 'test engineer': 152,
 'interface': 153,
 'color psychology': 154,
 'testing phases': 155,
 'collaborative development': 156,
 'patterns': 157,
 'continuous improvement': 158,
 'api': 159,
 'data preprocessing': 160,
 'unit testing': 161,
 'data governance': 162,
 'security': 163,
 'data scientist': 164,
 'interactive design': 165,
 'automation': 166,
 'stress testing': 167,
 'visualization': 168,
 'defect detection': 169,
 'iterative design': 170,
 'data science': 171,
 'source code management': 172,
 'usability principles': 173,
 'security assessment': 174,
 'api design': 175,
 'product owner': 176,
 'ui/ux design software': 177,
 'software development practices': 178,
 'design ethics': 179,
 'information architecture': 180,
 'data security': 181,
 'authentication': 182,
 'user verification': 183,
 'authorization': 184,
 'scrum': 185,
 'cleaning': 186,
 'test comprehensiveness': 187,
 'scrum roles': 188,
 'design': 189,
 'social engineering': 190,
 'agile manifesto': 191,
 'testing efficiency': 192,
 'two factor authentication': 193,
 'nosql': 194,
 'user centered design': 195,
 'data driven decision making': 196,
 'agile software development': 197,
 'software development lifecycle': 198,
 'data dashboards': 199,
 'access control': 200,
 'stakeholder collaboration': 201,
 'processing': 202,
 'mobile app development': 203,
 'responsive design': 204,
 'feature evaluation': 205,
 'testing changes': 206,
 'software integration': 207,
 'dry principle': 208,
 'visual perception': 209,
 'acceptance criteria': 210,
 'documentation': 211,
 'security analyst': 212,
 'statistical analysis': 213,
 'account security': 214,
 'web services': 215,
 'vulnerability assessment': 216,
 'structured query language': 217,
 'development': 218,
 'data analytics': 219,
 'visual design': 220,
 'software development': 221,
 'vulnerability management': 222,
 'dashboard': 223,
 'complementary colors': 224,
 'least privilege,principle of least privilege': 225,
 'exploratory data analysis': 226,
 'cybersecurity': 227,
 'application programming interface': 228,
 'data': 229,
 'testing processes': 230,
 'user interface design': 231,
 'code reusability': 232,
 'multi factor authentication': 233,
 'user feedback': 234,
 'design process': 235,
 'learning culture': 236,
 'information hierarchy': 237,
 'technical writer': 238,
 'build stability': 239,
 'compliance': 240,
 'model performance': 241,
 'cross platform testing': 242,
 'user navigation': 243,
 'data cleaning': 244,
 'data ethics': 245,
 'data protection': 246,
 'graphic design': 247,
 'database querying': 248,
 'information security compliance': 249,
 'data processing': 250,
 'principles': 251,
 'a/b testing': 252,
 'information security': 253,
 'defect identification': 254,
 'consistency,gestalt principles': 255,
 'vulnerability': 256,
 'data quality': 257,
 'color schemes': 258,
 'ci/cd': 259,
 'software quality assurance': 260,
 'git workflow': 261,
 'fail cheap': 262,
 'median': 263,
 'code quality': 264,
 'knowledge transfer': 265,
 'organizational security': 266,
 'elements': 267,
 'spear phishing': 268,
 'testing extremes': 269,
 'centralized version control': 270,
 'java': 271,
 'interaction design': 272,
 'user experience optimization': 273,
 'data analysis': 274,
 'testing metrics': 275,
 'code maintainability': 276,
 'encryption': 277,
 'usability evaluation': 278,
 'customer feedback': 279,
 'android development': 280,
 'mysql': 281,
 'mobile responsiveness': 282,
 'metadata': 283,
 'load testing': 284,
 'data visualization': 285}

In [19]:
df['skills_list'] = df['skills_list'].apply(lambda skills: [skill_mapping.get(skill) for skill in skills if skill in skill_mapping])
df.head()

,question_id,question,description,options,skills_list,correct_option,field_id
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"[""To track changes in code"", ""To format text"",...","[130, 172, 156, 83]",0,1
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"[""Don""t Repeat Yourself"", ""Design Reusable Yie...","[65, 208, 232, 67, 251]",0,1
2,3,Which programming language is known for its us...,Identify the programming language commonly ass...,"[""Java"", ""Python"", ""Ruby"", ""C++""]","[280, 125, 203, 2, 69, 271, 37, 57, 218]",0,1
3,4,"What does the term ""API"" stand for in software...",Select one option you think is right.,"[""Application Programming Interface"",""Advanced...","[159, 207, 215, 228]",0,1
4,5,What is the primary purpose of unit testing in...,Select the main objective of unit testing.,"[""To test individual components or functions"",...","[161, 50, 264, 52, 99, 5, 25]",0,1

In [20]:
test_df = df.explode('skills_list')
# get only question_id and skills_list
test_df = test_df[['question_id', 'skills_list']]
test_df

    question_id skills_list
0             1         130
0             1         172
0             1         156
0             1          83
1             2          65
..          ...         ...
88           89         187
89           90          13
89           90         260
89           90         242
89           90          72

[393 rows x 2 columns]

In [21]:
test_df = test_df.rename(columns={'skills_list': 'skill_id'})
test_df

    question_id skill_id
0             1      130
0             1      172
0             1      156
0             1       83
1             2       65
..          ...      ...
88           89      187
89           90       13
89           90      260
89           90      242
89           90       72

[393 rows x 2 columns]

In [22]:
# add test_skill_id column
test_df['id'] = np.arange(len(test_df)) + 1
test_df

    question_id skill_id   id
0             1      130    1
0             1      172    2
0             1      156    3
0             1       83    4
1             2       65    5
..          ...      ...  ...
88           89      187  389
89           90       13  390
89           90      260  391
89           90      242  392
89           90       72  393

[393 rows x 3 columns]

In [23]:
# reorder columns
test_df = test_df[['id', 'question_id', 'skill_id']]
test_df

     id  question_id skill_id
0     1            1      130
0     2            1      172
0     3            1      156
0     4            1       83
1     5            2       65
..  ...          ...      ...
88  389           89      187
89  390           90       13
89  391           90      260
89  392           90      242
89  393           90       72

[393 rows x 3 columns]

In [24]:
# save to csv
test_df.to_csv('../../static/csv/assessment_test_skills.csv', index=False)

In [25]:
df = pd.read_csv('../../static/csv/assessment_test_skills.csv')
df.head()

   id  question_id  skill_id
0   1            1       130
1   2            1       172
2   3            1       156
3   4            1        83
4   5            2        65

In [26]:
df.tail()

      id  question_id  skill_id
388  389           89       187
389  390           90        13
390  391           90       260
391  392           90       242
392  393           90        72

In [35]:
# # reodercolumns
# df = df[['id', 'skill_id','test_id' ]]
# df.head()

KeyError: "['test_id'] not in index"

In [27]:
# rename column question_id to test_id
df = df.rename(columns={'question_id': 'test_id'})

In [28]:
# save to csv
df.to_csv('../../static/csv/assessment_test_skills.csv', index=False)

# For Test_3, that have more test questions

In [35]:
import pandas as pd
import numpy as np
import ast

In [57]:
df = pd.read_csv('../../static/csv/test_3.csv')
df.head(2)

,question_id,question,description,options,correct_option,field_id,skills_list
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"['To track changes in code', 'To format text',...",0,1,"['version control', 'source code management', ..."
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"['Don't Repeat Yourself', 'Design Reusable Yie...",0,1,"['software development principles', 'dry princ..."

In [64]:
df2 = pd.read_csv('../../static/csv/test_4.csv')
df2.head(2)

,question_id,question,description,options,correct_option,field_id,skills_list
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"[""To track changes in code"", ""To format text"",...",0,1,"['Version Control','Source Code Management','C..."
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"[""Don""t Repeat Yourself"", ""Design Reusable Yie...",0,1,"[""Software Development Principles"",""DRY Princi..."

In [62]:
# on options column replace ' wtih ""
df2['options'] = df2['options'].apply(lambda x: x.replace("'", '"'))
df2.head(2)

,question_id,question,description,options,correct_option,field_id,skills_list
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"[""To track changes in code"", ""To format text"",...",0,1,"['Version Control','Source Code Management','C..."
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"[""Don""t Repeat Yourself"", ""Design Reusable Yie...",0,1,"['Software Development Principles','DRY Princi..."

In [63]:
# remove columns kills_list
df2 = df2.drop(columns=['skills_list'])

In [52]:
df2.head(2)

,question_id,question,description,options,correct_option,field_id
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"[""To track changes in code"", ""To format text"",...",0,1
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"[""Don""t Repeat Yourself"", ""Design Reusable Yie...",0,1

In [54]:
# convert options to JSON format
import json
# make to JSON string
df2['options'] = df2['options'].apply(lambda x: json.dumps(x))
df2.head(2)

,question_id,question,description,options,correct_option,field_id
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"""[\""To track changes in code\"", \""To format te...",0,1
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"""[\""Don\""t Repeat Yourself\"", \""Design Reusabl...",0,1

In [55]:
# save to csv
df2.to_csv('../../static/csv/assessment_test.csv', index=False)

In [6]:
# Convert the string representation of lists into actual lists
df['skills_list'] = df['skills_list'].apply(ast.literal_eval)
df.head(3)

,question_id,question,description,options,correct_option,field_id,skills_list
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"['To track changes in code', 'To format text',...",0,1,"[version control, source code management, coll..."
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"['Don't Repeat Yourself', 'Design Reusable Yie...",0,1,"[software development principles, dry principl..."
2,3,Which programming language is known for its us...,Identify the programming language commonly ass...,"['Java', 'Python', 'Ruby', 'C++']",0,1,"[android development, java programming, mobile..."

In [7]:
# to lower case
df['skills_list'] = df['skills_list'].apply(lambda x: [y.lower() for y in x])
df.head()

,question_id,question,description,options,correct_option,field_id,skills_list
0,1,What is the purpose of a version control syste...,Select the most accurate answer related to ver...,"['To track changes in code', 'To format text',...",0,1,"[version control, source code management, coll..."
1,2,What does DRY stand for in software development?,Choose the correct expansion of the acronym DRY.,"['Don't Repeat Yourself', 'Design Reusable Yie...",0,1,"[software development principles, dry principl..."
2,3,Which programming language is known for its us...,Identify the programming language commonly ass...,"['Java', 'Python', 'Ruby', 'C++']",0,1,"[android development, java programming, mobile..."
3,4,"What does the term ""API"" stand for in software...",Select one option you think is right.,"['Application Programming Interface','Advanced...",0,1,"[api, software integration, web services]"
4,5,What is the primary purpose of unit testing in...,Select the main objective of unit testing.,"['To test individual components or functions',...",0,1,"[unit testing, software testing, code quality]"

In [8]:
# remove strings 'skills' and 'skill'
df['skills_list'] = df['skills_list'].apply(lambda x: [y.replace('skills', '') for y in x])
df['skills_list'] = df['skills_list'].apply(lambda x: [y.replace('skill', '') for y in x])

In [10]:
# strip
df['skills_list'] = df['skills_list'].apply(lambda x: [y.strip() for y in x])
# replace '-' to ' '
df['skills_list'] = df['skills_list'].apply(lambda x: [y.replace('-', ' ') for y in x])

In [11]:
# remove empty
df['skills_list'] = df['skills_list'].apply(lambda x: [y for y in x if y != ''])

In [12]:
# Create a list of skills by combining all the skills from the 'skills_list' column
all_skills = [skill for skills_list in df['skills_list'] for skill in skills_list]

# Now, 'all_skills' contains all the skills from the DataFrame
print(all_skills)

['version control', 'source code management', 'collaborative development', 'software development principles', 'dry principle', 'code reusability', 'android development', 'java programming', 'mobile app development', 'api', 'software integration', 'web services', 'unit testing', 'software testing', 'code quality', 'data cleaning', 'data preprocessing', 'data analysis', 'data visualization', 'data analytics', 'data dashboards', 'tableau', 'data visualization', 'data analytics', 'data dashboards', 'tableau', 'sql', 'database querying', 'database management', 'statistics', 'median', 'data analysis', 'design principles', 'consistency in design', 'user interface design', 'color theory', 'complementary colors', 'color schemes', 'user testing', 'user experience testing', 'usability evaluation', 'design tools', 'wireframing', 'prototyping', 'ui/ux design software', 'product management', 'product manager', 'feature prioritization', 'product roadmap', 'product planning', 'product strategy', 'agile methodology', 'iterative development', 'customer feedback', 'scrum', 'product strategy', 'product documentation', 'product goals', 'mvp', 'product development', 'product launch', 'software testing', 'quality assurance', 'defect detection', 'regression testing', 'software testing', 'testing changes', 'load testing', 'software testing', 'performance testing', 'usability testing', 'user experience testing', 'user centered design', 'usability testing', 'user experience testing', 'user centered design', 'usability testing', 'user experience testing', 'user centered design', 'identity verification', 'authentication', 'access control', 'identity verification', 'authentication', 'access control', 'identity verification', 'authentication', 'access control', 'access control', 'security principles', 'authorization', 'access control', 'security principles', 'authorization', 'version control', 'git', 'svn', 'source code management', 'git', 'version control', 'collaborative development', 'code review', 'software development', 'collaborative development', 'continuous integration', 'ci/cd', 'software development practices', 'software architecture', 'software development', 'role of a software architect', 'devops', 'collaboration', 'continuous integration', 'software development practices', 'restful api', 'web services', 'api design', 'software development', 'agile software development', 'agile manifesto', 'scrum', 'software development principles', 'scrum framework', 'product owner', 'agile development', 'scrum roles', 'solid principles', 'object oriented design', 'software architecture', 'code maintainability', 'exploratory data analysis', 'data science', 'data analysis', 'statistical analysis', 'data preprocessing', 'machine learning', 'feature engineering', 'model performance', 'data dictionary', 'database management', 'metadata', 'data governance', 'big data', 'data processing', 'data analytics', 'nosql', 'data scientist', 'data analysis', 'predictive modeling', 'data driven decision making', 'data governance', 'data management', 'data quality', 'compliance', 'machine learning', 'data analysis', 'predictive modeling', 'pattern recognition', 'a/b testing', 'experimentation', 'data driven decision making', 'statistical analysis', 'data ethics', 'ethical data use', 'privacy', 'responsible ai', 'data security', 'data management', 'information security', 'cybersecurity', 'typography', 'graphic design', 'visual communication', 'brand identity', 'responsive design', 'user experience', 'web design', 'mobile responsiveness', 'information architecture', 'web design', 'user navigation', 'content organization', 'color psychology', 'design principles', 'emotional design', 'visual perception', 'motion design', 'user interfaces', 'interactive design', 'animation', 'user personas', 'user centered design', 'ux design', 'empathy in design', 'accessibility', 'inclusive design', 'usability', 'design ethics', 'prototyping', 'design process', 'user testing', 'iterative design', 'wireframing', 'ui/ux design', 'user interface', 'information hierarchy', 'interaction design', 'user interface design', 'usability principles', 'design guidelines', 'scrum framework', 'agile development', 'scrum master', 'agile practices', 'iterative development', 'product success', 'agile principles', 'adaptability in development', 'product owner', 'agile development', 'product backlog', 'stakeholder collaboration', 'user feedback', 'product development', 'usability testing', 'iterative design', 'lean product development', 'lean thinking', 'agile principles', 'continuous improvement', 'mvp', 'product development', 'product launch', 'lean startup', 'fail fast', 'fail cheap', 'innovation', 'risk taking', 'learning culture', 'technical writer', 'documentation', 'software development process', 'knowledge transfer', 'devops', 'software development lifecycle', 'continuous integration', 'automation', 'a/b testing', 'product development', 'user experience optimization', 'feature evaluation', 'two factor authentication', 'cybersecurity', 'account security', 'authentication methods', 'security analyst', 'cybersecurity', 'information security', 'security measures', 'endpoint security', 'cybersecurity', 'network security', 'device protection', 'social engineering', 'cybersecurity threats', 'information manipulation', 'phishing attacks', 'security policy', 'organizational security', 'information security compliance', 'security measures', 'penetration testing', 'cybersecurity', 'security assessment', 'vulnerability identification', 'information security', 'security principles', 'data protection', 'security controls', 'biometric authentication', 'user verification', 'cybersecurity', 'identity management', 'vulnerability management', 'cybersecurity', 'security assessment', 'threat mitigation', 'security incident response plan', 'cybersecurity', 'incident management', 'security incident handling', 'user acceptance testing', 'software testing', 'quality assurance', 'acceptance criteria', 'test engineer', 'software testing', 'quality assurance', 'testing processes', 'exploratory testing', 'software testing', 'defect identification', 'testing methods', 'stress testing', 'software quality assurance', 'performance evaluation', 'testing extremes', 'smoke testing', 'software testing', 'build stability', 'testing phases', 'black box testing', 'software quality assurance', 'defect identification', 'testing techniques', 'regression testing', 'software development life cycle', 'quality assurance', 'testing existing functionality', 'automated testing', 'software quality assurance', 'testing efficiency', 'test automation tools', 'code coverage', 'software testing', 'testing metrics', 'test comprehensiveness', 'compatibility testing', 'software quality assurance', 'cross platform testing', 'environment compatibility']

In [15]:
len(all_skills)

231

In [14]:
# remove duplicates
all_skills = list(set(all_skills))

### Since all skils are similar to current skills from before, we don't need to add it on the skill list

lets check if there are any unique skills from this

In [24]:
# load skill_4.csv
skill_df = pd.read_csv('../../static/csv/skill_4.csv')

In [18]:
# into list
skill_list = skill_df['skill'].tolist()

In [19]:
# get sample 
sample = np.random.choice(skill_list, 10)
print(sample)

['data conversion' 'executive management' 'unix administration'
 'dreamweaver' 'ux' 'web application developer' 'communication' 'prime'
 'system admin' 'sap scripts']

In [20]:
# check if there are skills from all_skills that are not in skill_list
for skill in all_skills:
    if skill not in skill_list:
        print(skill)

In [23]:
# get unique skills that are not in skill_list
unique_skills = [skill for skill in all_skills if skill not in skill_list]
print(unique_skills)

[]

In [25]:
skill_mapping = skill_df.set_index('skill')['id'].to_dict()

In [26]:
df.sample(3)

,question_id,question,description,options,correct_option,field_id,skills_list
68,69,How does DevOps contribute to the software dev...,Explain the principles and benefits of integra...,['Facilitates collaboration between developmen...,0,4,"[devops, software development lifecycle, conti..."
40,41,What is the importance of exploratory data ana...,Explain the significance of exploratory data a...,['Gain insights into data distributions and pa...,0,2,"[exploratory data analysis, data science, data..."
83,84,Define the term 'Stress Testing' in the contex...,Explain what Stress Testing involves and its s...,['Assesses software behavior under extreme con...,0,5,"[stress testing, software quality assurance, p..."

In [27]:
# apply skill_mapping to skills_list
df['skills_list'] = df['skills_list'].apply(lambda skills: [skill_mapping.get(skill) for skill in skills if skill in skill_mapping])
df.sample(3)

In [29]:
# explode skills_list
df = df.explode('skills_list')

In [30]:
# get only question_id and skills_list
df = df[['question_id', 'skills_list']]
df.head()

   question_id skills_list
0            1         130
0            1         208
0            1         126
1            2         198
1            2         192

In [31]:
# rename
df = df.rename(columns={'skills_list': 'skill_id'})
df.head()

   question_id skill_id
0            1      130
0            1      208
0            1      126
1            2      198
1            2      192

In [32]:
# add skill_id column
df['id'] = np.arange(len(df)) + 1
df.head()

   question_id skill_id  id
0            1      130   1
0            1      208   2
0            1      126   3
1            2      198   4
1            2      192   5

In [33]:
# reorder columns
df = df[['id', 'question_id', 'skill_id']]
df.head()

   id  question_id skill_id
0   1            1      130
0   2            1      208
0   3            1      126
1   4            2      198
1   5            2      192

In [34]:
# sve to csv
df.to_csv('../../static/csv/assessment_test_skills.csv', index=False)

# Test Skills for Fields

In [2]:
import pandas as pd

In [4]:
# load csv
test = pd.read_csv('../../static/csv/test_5.csv')
test.sample()

,question_id,question,description,options,skills_list,correct_option,field_id
2,3,Which programming language is known for its us...,Identify the programming language commonly ass...,"[""Java"", ""Python"", ""Ruby"", ""C++""]","[""Android Development"",""Java Programming"",""Mob...",0,1

In [5]:
import ast
# apply ast to skills
test['skills_list'] = test['skills_list'].apply(ast.literal_eval)
test.sample()

,question_id,question,description,options,skills_list,correct_option,field_id
39,40,What is the purpose of the SOLID principles in...,Explain the significance of the SOLID principl...,"[""Guidelines for designing maintainable and sc...","[SOLID Principles, Object-Oriented Design, Sof...",0,1

In [6]:
# lower case
test['skills_list'] = test['skills_list'].apply(lambda x: [y.lower() for y in x])
# remove skill and skills
test['skills_list'] = test['skills_list'].apply(lambda x: [y.replace('skill', '') for y in x])
# remove '-'
test['skills_list'] = test['skills_list'].apply(lambda x: [y.replace('-', ' ') for y in x])
# stirp
test['skills_list'] = test['skills_list'].apply(lambda x: [y.strip() for y in x])
# remove empty stirngs ''
test['skills_list'] = test['skills_list'].apply(lambda x: [y for y in x if y != ''])

In [7]:
test.sample(5)

,question_id,question,description,options,skills_list,correct_option,field_id
17,18,What methodology emphasizes iterative developm...,Select the methodology focused on iterative de...,"[""Agile"", ""Waterfall"", ""Six Sigma"", ""Scrum""]","[agile methodology, iterative development, cus...",0,4
84,85,What is the purpose of 'Smoke Testing' in soft...,Select the main objective of Smoke Testing in ...,"[""To quickly determine if the software build i...","[smoke testing, software testing, build stabil...",0,5
56,57,What is the importance of accessibility in des...,Explain the significance of designing products...,"[""Ensures inclusivity and usability for all us...","[accessibility, inclusive design, usability, d...",0,3
25,26,What is the practice of disguising information...,Select the security practice that involves dis...,"[""Encryption"", ""Decryption"", ""Authentication"",...","[data security, encryption, data masking, mask...",0,6
81,82,What is the role of a Test Engineer in softwar...,Describe the responsibilities of a Test Engine...,"[""Designs and develops test cases and test pla...","[test engineer, software testing, quality assu...",0,5

In [10]:
# get all skills
all_skills = [skill for skills_list in test['skills_list'] for skill in skills_list]
print(all_skills)

['version control', 'source code management', 'collaborative development', 'vcs', 'software development principles', 'dry principle', 'code reusability', 'dry', 'principles', 'android development', 'java programming', 'mobile app development', 'android', 'app', 'java', 'programming', 'mobile', 'development', 'api', 'software integration', 'web services', 'application programming interface', 'unit testing', 'software testing', 'code quality', 'testing', 'unit', 'test', 'quality', 'data cleaning', 'data preprocessing', 'data analysis', 'cleaning', 'processing', 'data', 'data science', 'data analytics', 'data visualization', 'data analytics', 'data dashboards', 'tableau', 'dashboards', 'dashboard', 'visualization', 'analytics', 'data visualization', 'data analytics', 'data dashboards', 'tableau', 'patterns', 'pattern recognition', 'insights', 'data', 'analytics', 'visualization', 'dashboard', 'sql', 'database querying', 'database management', 'database', 'db', 'mysql', 'structured query language', 'statistics', 'median', 'data analysis', 'analytics', 'statistics', 'math', 'design principles', 'consistency in design', 'user interface design', 'interface', 'user', 'design', 'visual design', 'design principles', 'consistency,gestalt principles', 'color theory', 'complementary colors', 'color schemes', 'color', 'design', 'elements', 'user testing', 'user experience testing', 'usability evaluation', 'design tools', 'wireframing', 'prototyping', 'ui/ux design software', 'product management', 'product manager', 'feature prioritization', 'product roadmap', 'product planning', 'product strategy', 'agile methodology', 'iterative development', 'customer feedback', 'scrum', 'product strategy', 'product documentation', 'product goals', 'mvp', 'product development', 'product launch', 'software testing', 'quality assurance', 'defect detection', 'regression testing', 'software testing', 'testing changes', 'load testing', 'software testing', 'performance testing', 'software testing', 'penetration testing', 'vulnerability assessment', 'testing', 'penetration', 'vulnerability', 'assessment', 'usability testing', 'user experience testing', 'user centered design', 'data security', 'encryption', 'data masking', 'masking', 'security', 'cybersecurity', 'social engineering', 'spear phishing', 'identity verification', 'authentication', 'authorization', 'multi factor authentication', 'network security', 'firewall', 'network perimeter protection', 'security', 'network', 'protection', 'access control', 'security principles', 'authorization', 'access control', 'least privilege,principle of least privilege', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'code review', 'software development', 'collaborative development', 'continuous integration', 'ci/cd', 'software development practices', 'software architecture', 'software development', 'role of a software architect', 'devops', 'collaboration', 'continuous integration', 'software development practices', 'restful api', 'web services', 'api design', 'software development', 'agile software development', 'agile manifesto', 'scrum', 'software development principles', 'scrum framework', 'product owner', 'agile development', 'scrum roles', 'solid principles', 'object oriented design', 'software architecture', 'code maintainability', 'exploratory data analysis', 'data science', 'data analysis', 'statistical analysis', 'data preprocessing', 'machine learning', 'feature engineering', 'model performance', 'data dictionary', 'database management', 'metadata', 'data governance', 'big data', 'data processing', 'data analytics', 'nosql', 'data scientist', 'data analysis', 'predictive modeling', 'data driven decision making', 'data governance', 'data management', 'data quality', 'compliance', 'machine learning', 'data analysis', 'predictive modeling', 'pattern recognition', 'a/b testing', 'experimentation', 'data driven decision making', 'statistical analysis', 'data ethics', 'ethical data use', 'privacy', 'responsible ai', 'data security', 'data management', 'information security', 'cybersecurity', 'typography', 'graphic design', 'visual communication', 'brand identity', 'responsive design', 'user experience', 'web design', 'mobile responsiveness', 'information architecture', 'web design', 'user navigation', 'content organization', 'color psychology', 'design principles', 'emotional design', 'visual perception', 'motion design', 'user interfaces', 'interactive design', 'animation', 'user personas', 'user centered design', 'ux design', 'empathy in design', 'accessibility', 'inclusive design', 'usability', 'design ethics', 'prototyping', 'design process', 'user testing', 'iterative design', 'wireframing', 'ui/ux design', 'user interface', 'information hierarchy', 'interaction design', 'user interface design', 'usability principles', 'design guidelines', 'scrum framework', 'agile development', 'scrum master', 'agile practices', 'iterative development', 'product success', 'agile principles', 'adaptability in development', 'product owner', 'agile development', 'product backlog', 'stakeholder collaboration', 'user feedback', 'product development', 'usability testing', 'iterative design', 'lean product development', 'lean thinking', 'agile principles', 'continuous improvement', 'mvp', 'product development', 'product launch', 'lean startup', 'fail fast', 'fail cheap', 'innovation', 'risk taking', 'learning culture', 'technical writer', 'documentation', 'software development process', 'knowledge transfer', 'devops', 'software development lifecycle', 'continuous integration', 'automation', 'a/b testing', 'product development', 'user experience optimization', 'feature evaluation', 'two factor authentication', 'account security', 'authentication methods', 'security analyst', 'cybersecurity', 'information security', 'security measures', 'endpoint security', 'security', 'network security', 'device protection', 'social engineering', 'cybersecurity threats', 'information manipulation', 'phishing attacks', 'security policy', 'organizational security', 'information security compliance', 'security measures', 'penetration testing', 'cybersecurity', 'security assessment', 'vulnerability identification', 'information security', 'security principles', 'data protection', 'security controls', 'biometric authentication', 'user verification', 'cybersecurity', 'identity management', 'vulnerability management', 'security', 'security assessment', 'threat mitigation', 'security incident response plan', 'incident management', 'security incident handling', 'security', 'incident', 'user acceptance testing', 'software testing', 'quality assurance', 'acceptance criteria', 'test engineer', 'software testing', 'quality assurance', 'testing processes', 'exploratory testing', 'software testing', 'defect identification', 'testing methods', 'stress testing', 'software quality assurance', 'performance evaluation', 'testing extremes', 'smoke testing', 'software testing', 'build stability', 'testing phases', 'black box testing', 'software quality assurance', 'defect identification', 'testing techniques', 'regression testing', 'software development life cycle', 'quality assurance', 'testing existing functionality', 'automated testing', 'software quality assurance', 'testing efficiency', 'test automation tools', 'code coverage', 'software testing', 'testing metrics', 'test comprehensiveness', 'compatibility testing', 'software quality assurance', 'cross platform testing', 'environment compatibility']

In [11]:
len(all_skills)

393

In [12]:
# unique skills
unique_skills = list(set(all_skills))
print(unique_skills)

['usability evaluation', 'testing efficiency', 'visual communication', 'product manager', 'continuous improvement', 'product roadmap', 'testing extremes', 'encryption', 'inclusive design', 'documentation', 'security incident handling', 'android development', 'prototyping', 'statistical analysis', 'agile development', 'penetration', 'role of a software architect', 'solid principles', 'organizational security', 'testing phases', 'authentication', 'complementary colors', 'predictive modeling', 'test engineer', 'application programming interface', 'privacy', 'responsive design', 'user verification', 'user navigation', 'testing metrics', 'agile practices', 'information security', 'cross platform testing', 'math', 'masking', 'quality assurance', 'data preprocessing', 'compliance', 'information hierarchy', 'mysql', 'code coverage', 'structured query language', 'svn', 'lean thinking', 'risk taking', 'collaborative development', 'user interfaces', 'fail cheap', 'database', 'exploratory testing', 'api design', 'version control', 'two factor authentication', 'product management', 'empathy in design', 'user experience optimization', 'content organization', 'cleaning', 'wireframing', 'distributed version control', 'data quality', 'threat mitigation', 'java programming', 'unit testing', 'graphic design', 'usability testing', 'data ethics', 'stakeholder collaboration', 'security policy', 'insights', 'software development principles', 'assessment', 'code quality', 'accessibility', 'vulnerability', 'object oriented design', 'data analytics', 'interface', 'security incident response plan', 'defect detection', 'environment compatibility', 'elements', 'pattern recognition', 'data cleaning', 'emotional design', 'dashboard', 'design tools', 'cybersecurity', 'firewall', 'security assessment', 'data masking', 'incident management', 'performance evaluation', 'ci/cd', 'git', 'phishing attacks', 'vulnerability management', 'scrum framework', 'a/b testing', 'web services', 'user testing', 'mobile responsiveness', 'testing', 'stress testing', 'analytics', 'model performance', 'android', 'testing techniques', 'principles', 'design', 'penetration testing', 'product documentation', 'software integration', 'dry principle', 'data visualization', 'color psychology', 'data dashboards', 'product goals', 'data security', 'incident', 'data', 'feature engineering', 'account security', 'devops', 'test', 'user centered design', 'regression testing', 'color theory', 'protection', 'mobile app development', 'product launch', 'usability', 'interaction design', 'usability principles', 'device protection', 'authentication methods', 'lean product development', 'information security compliance', 'interactive design', 'network', 'development', 'agile methodology', 'design ethics', 'security principles', 'product backlog', 'user interface', 'access control', 'data management', 'smoke testing', 'continuous integration', 'patterns', 'data dictionary', 'database querying', 'testing changes', 'user interface design', 'centralized version control', 'user acceptance testing', 'consistency,gestalt principles', 'multi factor authentication', 'mobile', 'scrum roles', 'load testing', 'iterative design', 'visual perception', 'experimentation', 'scrum', 'responsible ai', 'app', 'defect identification', 'design process', 'spear phishing', 'metadata', 'vcs', 'social engineering', 'learning culture', 'security analyst', 'source code management', 'security controls', 'data analysis', 'visualization', 'median', 'software architecture', 'feature evaluation', 'mvp', 'authorization', 'biometric authentication', 'software quality assurance', 'user feedback', 'least privilege,principle of least privilege', 'lean startup', 'color', 'user experience testing', 'build stability', 'statistics', 'product strategy', 'software development life cycle', 'dry', 'cybersecurity threats', 'db', 'product owner', 'code maintainability', 'knowledge transfer', 'quality', 'network perimeter protection', 'data science', 'nosql', 'software development process', 'iterative development', 'security measures', 'code reusability', 'restful api', 'agile software development', 'ux design', 'tableau', 'vulnerability assessment', 'automated testing', 'customer feedback', 'data protection', 'database management', 'innovation', 'test comprehensiveness', 'software development practices', 'security', 'api', 'machine learning', 'product development', 'design guidelines', 'design principles', 'git workflow', 'testing processes', 'scrum master', 'code review', 'exploratory data analysis', 'processing', 'ethical data use', 'fail fast', 'ui/ux design', 'test automation tools', 'black box testing', 'unit', 'brand identity', 'agile manifesto', 'product planning', 'big data', 'collaboration', 'dashboards', 'technical writer', 'endpoint security', 'compatibility testing', 'data scientist', 'automation', 'sql', 'software development lifecycle', 'testing existing functionality', 'visual design', 'data driven decision making', 'network security', 'data governance', 'animation', 'programming', 'acceptance criteria', 'motion design', 'software development', 'testing methods', 'ui/ux design software', 'feature prioritization', 'identity verification', 'adaptability in development', 'user personas', 'typography', 'consistency in design', 'java', 'software testing', 'identity management', 'performance testing', 'user experience', 'information architecture', 'user', 'data processing', 'information manipulation', 'vulnerability identification', 'color schemes', 'product success', 'web design', 'agile principles']

In [13]:
len(unique_skills)

285

In [8]:
test['skill_list'] = test['skills_list'].apply(lambda x: eval(x) if isinstance(x, str) else x)
grouped_test = test.groupby('field_id')['skill_list'].agg(sum).reset_index()

In [9]:
grouped_test

   field_id                                         skill_list
0         1  [version control, source code management, coll...
1         2  [data cleaning, data preprocessing, data analy...
2         3  [design principles, consistency in design, use...
3         4  [product management, product manager, feature ...
4         5  [software testing, quality assurance, defect d...
5         6  [data security, encryption, data masking, mask...

In [31]:
# save to csv
grouped_test.to_csv('../../static/csv/field_skill_001.csv', index=False)

In [32]:
# load subject_field.csv
subject_field = pd.read_csv('../../static/csv/subject_field.csv')
subject_field.head(2)

,id,subject_name,description,field_id,skill1,skill_list
0,1,Introduction to Computing,Introduction to Computing is a fundamental cou...,1,"'problem solving', 'programming', 'algorithms'","['problem solving', 'programming', 'algorithms']"
1,2,Computer Programming 1,Computer Programming 1 covers the basics of pr...,1,"'programming', 'coding', 'software development'","['programming', 'coding', 'software development']"

In [33]:
# used ast to convert string to list
subject_field['skill_list'] = subject_field['skill_list'].apply(ast.literal_eval)
subject_field.head(2)

,id,subject_name,description,field_id,skill1,skill_list
0,1,Introduction to Computing,Introduction to Computing is a fundamental cou...,1,"'problem solving', 'programming', 'algorithms'","[problem solving, programming, algorithms]"
1,2,Computer Programming 1,Computer Programming 1 covers the basics of pr...,1,"'programming', 'coding', 'software development'","[programming, coding, software development]"

In [34]:
# lover case
subject_field['skill_list'] = subject_field['skill_list'].apply(lambda x: [y.lower() for y in x])
# remove '-'
subject_field['skill_list'] = subject_field['skill_list'].apply(lambda x: [y.replace('-', ' ') for y in x])
# remove skill and skills
subject_field['skill_list'] = subject_field['skill_list'].apply(lambda x: [y.replace('skill', '') for y in x])
subject_field['skill_list'] = subject_field['skill_list'].apply(lambda x: [y.replace('skills', '') for y in x])
# strip
subject_field['skill_list'] = subject_field['skill_list'].apply(lambda x: [y.strip() for y in x])
# remove empty strings
subject_field['skill_list'] = subject_field['skill_list'].apply(lambda x: [y for y in x if y != ''])

In [35]:
# group to field_id, combine skill_list
subject_field['skill_list'] = subject_field['skill_list'].apply(lambda x: eval(x) if isinstance(x, str) else x)
grouped_subject = subject_field.groupby('field_id')['skill_list'].agg(sum).reset_index()

In [36]:
grouped_test['skill_list'] = grouped_test['skill_list'].apply(lambda d: d if isinstance(d, list) else [])
grouped_test
#grouped_specialization['skill_list'] = grouped_specialization['skill_list'].apply(lambda d: d if isinstance(d, list) else [])

   field_id                                         skill_list
0         1  [version control, source code management, coll...
1         2  [data cleaning, data preprocessing, data analy...
2         3  [design principles, consistency in design, use...
3         4  [product management, product manager, feature ...
4         5  [software testing, quality assurance, defect d...
5         6  [data security, encryption, data masking, mask...

In [37]:
grouped_subject['skill_list'] = grouped_subject['skill_list'].apply(lambda d: d if isinstance(d, list) else [])
grouped_subject
#grouped_specialization['skill_list'] = grouped_specialization['skill_list'].apply(lambda d: d if isinstance(d, list) else [])

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [104]:
grouped_all = grouped_subject.copy()
grouped_all

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [105]:
grouped_test

   field_id                                         skill_list
0         1  [version control, source code management, coll...
1         2  [data cleaning, data preprocessing, data analy...
2         3  [design principles, consistency in design, use...
3         4  [product management, product manager, feature ...
4         5  [software testing, quality assurance, defect d...
5         6  [data security, encryption, data masking, mask...

In [106]:
# combine grouped_test and grouped_subject' skill_list
grouped_all['skill_list'] = grouped_subject['skill_list'] + grouped_test['skill_list']
grouped_all

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [107]:
# remove empty on skill_list
grouped_all['skill_list'] = grouped_all['skill_list'].apply(lambda x: [y for y in x if y != ''])
# remove NaN
grouped_all['skill_list'] = grouped_all['skill_list'].apply(lambda x: [y for y in x if str(y) != 'nan'])

In [108]:
# duplicate skill_list 5 times
grouped_all['skill_list'] = grouped_all['skill_list'].apply(lambda x: x * 5)

In [109]:
grouped_all

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [110]:
# grouped_subject = grouped_subject1

In [111]:
grouped_all['skill_list'] = grouped_all['skill_list'].apply(lambda d: d if isinstance(d, list) else [])
grouped_all
#grouped_specialization['skill_list'] = grouped_specialization['skill_list'].apply(lambda d: d if isinstance(d, list) else [])

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [72]:
# load specialization5_.csv
specialization = pd.read_csv('../../static/csv/specialization5_.csv')
specialization.head(2)

,specialization_id,title,field_id,description,roadmap_id,skill_list
0,1,Frontend Developer,1,Front-End Developers are responsible for creat...,1,"['html', 'css', 'javascript', 'web design', 'r..."
1,2,Backend Developer,1,Back-End Developers work on the server-side of...,2,"['node.js', 'python', 'ruby', 'java', 'databas..."

In [73]:
# used ast to convert string to list
specialization['skill_list'] = specialization['skill_list'].apply(ast.literal_eval)
# lower case
specialization['skill_list'] = specialization['skill_list'].apply(lambda x: [y.lower() for y in x])
# remove '-'
specialization['skill_list'] = specialization['skill_list'].apply(lambda x: [y.replace('-', ' ') for y in x])
# remove skill and skills
specialization['skill_list'] = specialization['skill_list'].apply(lambda x: [y.replace('skill', '') for y in x])
specialization['skill_list'] = specialization['skill_list'].apply(lambda x: [y.replace('skills', '') for y in x])
# strip
specialization['skill_list'] = specialization['skill_list'].apply(lambda x: [y.strip() for y in x])
# remove empty strings
specialization['skill_list'] = specialization['skill_list'].apply(lambda x: [y for y in x if y != ''])

In [90]:
# group to field_id, combine skill_list
specialization['skill_list'] = specialization['skill_list'].apply(lambda x: eval(x) if isinstance(x, str) else x)
grouped_specialization = specialization.groupby('field_id')['skill_list'].agg(sum).reset_index()

In [91]:
# get only field id 1-6
grouped_specialization = grouped_specialization[grouped_specialization['field_id'] <= 6]
grouped_specialization = grouped_specialization[grouped_specialization['field_id'] >= 1]
grouped_specialization

   field_id                                         skill_list
1         1  [html, css, javascript, web design, responsive...
2         2  [business intelligence tools, tableau, power b...
3         3  [user interface design, wireframing, prototypi...
4         4  [product management, roadmap planning, agile m...
5         5  [performance improvement, supply chain managem...
6         6  [cybersecurity principles, security tools, fir...

In [92]:
# check if ther is NaN in skill_list
grouped_specialization[grouped_specialization['skill_list'].isna()]

Empty DataFrame
Columns: [field_id, skill_list]
Index: []

In [93]:
# remove emtpy on skill_list
grouped_specialization['skill_list'] = grouped_specialization['skill_list'].apply(lambda x: [y for y in x if y != ''])
# remove NaN
grouped_specialization['skill_list'] = grouped_specialization['skill_list'].apply(lambda x: [y for y in x if str(y) != 'nan'])
# remove ' '
grouped_specialization['skill_list'] = grouped_specialization['skill_list'].apply(lambda x: [y for y in x if y != ' '])

In [94]:
grouped_subject

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [103]:
grouped_all

   field_id                                         skill_list
0         1                                                NaN
1         2  ['formal languages', 'automata theory', 'langu...
2         3  ['user experience', 'interface design', 'usabi...
3         4  ['data management', 'information organization'...
4         5  ['information security', 'cybersecurity', 'dat...
5         6  ['operating systems', 'system administration',...

In [96]:
grouped_specialization

   field_id                                         skill_list
1         1  [html, css, javascript, web design, responsive...
2         2  [business intelligence tools, tableau, power b...
3         3  [user interface design, wireframing, prototypi...
4         4  [product management, roadmap planning, agile m...
5         5  [performance improvement, supply chain managem...
6         6  [cybersecurity principles, security tools, fir...

In [121]:
grouped_all2 = grouped_all.copy()
grouped_all2

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [122]:
grouped_all2

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [112]:
# save group_all to csv
grouped_all.to_csv('../../static/csv/z_group_all.csv', index=False)
grouped_specialization.to_csv('../../static/csv/z_group_specialization.csv', index=False)

In [101]:
# load csv
grouped_all = pd.read_csv('../../static/csv/z_group_all.csv')
grouped_specialization = pd.read_csv('../../static/csv/z_group_specialization.csv')

In [120]:
grouped_all

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [114]:
grouped_specialization

   field_id                                         skill_list
0         1  ['html', 'css', 'javascript', 'web design', 'r...
1         2  ['business intelligence tools', 'tableau', 'po...
2         3  ['user interface design', 'wireframing', 'prot...
3         4  ['product management', 'roadmap planning', 'ag...
4         5  ['performance improvement', 'supply chain mana...
5         6  ['cybersecurity principles', 'security tools',...

In [118]:
# use ast to convert string to list
grouped_all['skill_list'] = grouped_all['skill_list'].apply(ast.literal_eval)

ValueError: malformed node or string: ['problem solving', 'programming', 'algorithms', 'programming', 'coding', 'software development', 'advanced programming', 'software development', 'algorithms', 'mathematics', 'data structures', 'computer science', 'modeling', 'simulation', 'analysis', 'data structures', 'algorithms', 'optimization', 'advanced mathematics', 'computer science', 'data analysis', 'object oriented design', 'software development', 'coding', 'digital circuits', 'logic design', 'electronics', 'algorithm design', 'problem solving', 'complexity analysis', 'computer architecture', 'assembly language', 'hardware', 'programming languages', 'language design', 'syntax', 'advanced software engineering', 'software development', 'project management', 'structured programming', 'problem solving', 'coding', 'integrative programming', 'technology integration', 'coding', 'application development', 'emerging technologies', 'software design', 'version control', 'source code management', 'collaborative development', 'vcs', 'software development principles', 'dry principle', 'code reusability', 'dry', 'principles', 'android development', 'java programming', 'mobile app development', 'android', 'app', 'java', 'programming', 'mobile', 'development', 'api', 'software integration', 'web services', 'application programming interface', 'unit testing', 'software testing', 'code quality', 'testing', 'unit', 'test', 'quality', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'code review', 'software development', 'collaborative development', 'continuous integration', 'ci/cd', 'software development practices', 'software architecture', 'software development', 'role of a software architect', 'devops', 'collaboration', 'continuous integration', 'software development practices', 'restful api', 'web services', 'api design', 'software development', 'agile software development', 'agile manifesto', 'scrum', 'software development principles', 'scrum framework', 'product owner', 'agile development', 'scrum roles', 'solid principles', 'object oriented design', 'software architecture', 'code maintainability', 'problem solving', 'programming', 'algorithms', 'programming', 'coding', 'software development', 'advanced programming', 'software development', 'algorithms', 'mathematics', 'data structures', 'computer science', 'modeling', 'simulation', 'analysis', 'data structures', 'algorithms', 'optimization', 'advanced mathematics', 'computer science', 'data analysis', 'object oriented design', 'software development', 'coding', 'digital circuits', 'logic design', 'electronics', 'algorithm design', 'problem solving', 'complexity analysis', 'computer architecture', 'assembly language', 'hardware', 'programming languages', 'language design', 'syntax', 'advanced software engineering', 'software development', 'project management', 'structured programming', 'problem solving', 'coding', 'integrative programming', 'technology integration', 'coding', 'application development', 'emerging technologies', 'software design', 'version control', 'source code management', 'collaborative development', 'vcs', 'software development principles', 'dry principle', 'code reusability', 'dry', 'principles', 'android development', 'java programming', 'mobile app development', 'android', 'app', 'java', 'programming', 'mobile', 'development', 'api', 'software integration', 'web services', 'application programming interface', 'unit testing', 'software testing', 'code quality', 'testing', 'unit', 'test', 'quality', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'code review', 'software development', 'collaborative development', 'continuous integration', 'ci/cd', 'software development practices', 'software architecture', 'software development', 'role of a software architect', 'devops', 'collaboration', 'continuous integration', 'software development practices', 'restful api', 'web services', 'api design', 'software development', 'agile software development', 'agile manifesto', 'scrum', 'software development principles', 'scrum framework', 'product owner', 'agile development', 'scrum roles', 'solid principles', 'object oriented design', 'software architecture', 'code maintainability', 'problem solving', 'programming', 'algorithms', 'programming', 'coding', 'software development', 'advanced programming', 'software development', 'algorithms', 'mathematics', 'data structures', 'computer science', 'modeling', 'simulation', 'analysis', 'data structures', 'algorithms', 'optimization', 'advanced mathematics', 'computer science', 'data analysis', 'object oriented design', 'software development', 'coding', 'digital circuits', 'logic design', 'electronics', 'algorithm design', 'problem solving', 'complexity analysis', 'computer architecture', 'assembly language', 'hardware', 'programming languages', 'language design', 'syntax', 'advanced software engineering', 'software development', 'project management', 'structured programming', 'problem solving', 'coding', 'integrative programming', 'technology integration', 'coding', 'application development', 'emerging technologies', 'software design', 'version control', 'source code management', 'collaborative development', 'vcs', 'software development principles', 'dry principle', 'code reusability', 'dry', 'principles', 'android development', 'java programming', 'mobile app development', 'android', 'app', 'java', 'programming', 'mobile', 'development', 'api', 'software integration', 'web services', 'application programming interface', 'unit testing', 'software testing', 'code quality', 'testing', 'unit', 'test', 'quality', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'code review', 'software development', 'collaborative development', 'continuous integration', 'ci/cd', 'software development practices', 'software architecture', 'software development', 'role of a software architect', 'devops', 'collaboration', 'continuous integration', 'software development practices', 'restful api', 'web services', 'api design', 'software development', 'agile software development', 'agile manifesto', 'scrum', 'software development principles', 'scrum framework', 'product owner', 'agile development', 'scrum roles', 'solid principles', 'object oriented design', 'software architecture', 'code maintainability', 'problem solving', 'programming', 'algorithms', 'programming', 'coding', 'software development', 'advanced programming', 'software development', 'algorithms', 'mathematics', 'data structures', 'computer science', 'modeling', 'simulation', 'analysis', 'data structures', 'algorithms', 'optimization', 'advanced mathematics', 'computer science', 'data analysis', 'object oriented design', 'software development', 'coding', 'digital circuits', 'logic design', 'electronics', 'algorithm design', 'problem solving', 'complexity analysis', 'computer architecture', 'assembly language', 'hardware', 'programming languages', 'language design', 'syntax', 'advanced software engineering', 'software development', 'project management', 'structured programming', 'problem solving', 'coding', 'integrative programming', 'technology integration', 'coding', 'application development', 'emerging technologies', 'software design', 'version control', 'source code management', 'collaborative development', 'vcs', 'software development principles', 'dry principle', 'code reusability', 'dry', 'principles', 'android development', 'java programming', 'mobile app development', 'android', 'app', 'java', 'programming', 'mobile', 'development', 'api', 'software integration', 'web services', 'application programming interface', 'unit testing', 'software testing', 'code quality', 'testing', 'unit', 'test', 'quality', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'code review', 'software development', 'collaborative development', 'continuous integration', 'ci/cd', 'software development practices', 'software architecture', 'software development', 'role of a software architect', 'devops', 'collaboration', 'continuous integration', 'software development practices', 'restful api', 'web services', 'api design', 'software development', 'agile software development', 'agile manifesto', 'scrum', 'software development principles', 'scrum framework', 'product owner', 'agile development', 'scrum roles', 'solid principles', 'object oriented design', 'software architecture', 'code maintainability', 'problem solving', 'programming', 'algorithms', 'programming', 'coding', 'software development', 'advanced programming', 'software development', 'algorithms', 'mathematics', 'data structures', 'computer science', 'modeling', 'simulation', 'analysis', 'data structures', 'algorithms', 'optimization', 'advanced mathematics', 'computer science', 'data analysis', 'object oriented design', 'software development', 'coding', 'digital circuits', 'logic design', 'electronics', 'algorithm design', 'problem solving', 'complexity analysis', 'computer architecture', 'assembly language', 'hardware', 'programming languages', 'language design', 'syntax', 'advanced software engineering', 'software development', 'project management', 'structured programming', 'problem solving', 'coding', 'integrative programming', 'technology integration', 'coding', 'application development', 'emerging technologies', 'software design', 'version control', 'source code management', 'collaborative development', 'vcs', 'software development principles', 'dry principle', 'code reusability', 'dry', 'principles', 'android development', 'java programming', 'mobile app development', 'android', 'app', 'java', 'programming', 'mobile', 'development', 'api', 'software integration', 'web services', 'application programming interface', 'unit testing', 'software testing', 'code quality', 'testing', 'unit', 'test', 'quality', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'version control', 'git', 'svn', 'source code management', 'distributed version control', 'centralized version control', 'git workflow', 'code review', 'software development', 'collaborative development', 'continuous integration', 'ci/cd', 'software development practices', 'software architecture', 'software development', 'role of a software architect', 'devops', 'collaboration', 'continuous integration', 'software development practices', 'restful api', 'web services', 'api design', 'software development', 'agile software development', 'agile manifesto', 'scrum', 'software development principles', 'scrum framework', 'product owner', 'agile development', 'scrum roles', 'solid principles', 'object oriented design', 'software architecture', 'code maintainability']

In [119]:
grouped_specialization['skill_list'] = grouped_specialization['skill_list'].apply(ast.literal_eval)
grouped_specialization

   field_id                                         skill_list
0         1  [html, css, javascript, web design, responsive...
1         2  [business intelligence tools, tableau, power b...
2         3  [user interface design, wireframing, prototypi...
3         4  [product management, roadmap planning, agile m...
4         5  [performance improvement, supply chain managem...
5         6  [cybersecurity principles, security tools, fir...

In [123]:
grouped_all2['skill_list'] = grouped_all2['skill_list'] + grouped_specialization['skill_list']
grouped_all2

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [124]:
# save to csv
grouped_all2.to_csv('../../static/csv/z_group_all2.csv', index=False)

In [125]:
# load csv
grouped_all2 = pd.read_csv('../../static/csv/z_group_all2.csv')

In [139]:
grouped_all2

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [127]:
# load coursera.csv
coursera = pd.read_csv('../../static/csv/coursera.csv')
coursera.head(2)

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills,skills_list,keywords,skill_list_2,skill_list_3,field_id
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...,"['drama', 'comedy', 'peering', 'screenwriting'...",write a feature length screenplay for film or ...,"['drama', 'comedy', 'peering', 'screenwriting'...","['document', 'review', 'dialogue', 'creative',...",0
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...,"['finance', 'business', 'plan', 'persona', '(u...",business strategy business model canvas analys...,"['finance', 'business', 'plan', 'persona', '(u...","['finance', 'business', 'plan', 'business', 'm...",0

In [128]:
# get field id 1-6
coursera = coursera[coursera['field_id'] <= 6]
coursera = coursera[coursera['field_id'] >= 1]
coursera

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills,skills_list,keywords,skill_list_2,skill_list_3,field_id
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...,"['data', 'analysis', 'select', '(sql)', 'datab...",retrieve data using singletable sql queriesret...,"['data', 'analysis', 'select', '(sql)', 'datab...","['data', 'analysis', 'database', 'management',...",2
5,Building Test Automation Framework using Selen...,Coursera Project Network,Beginner,4.7,https://www.coursera.org/learn/building-test-a...,Selenium is one of the most widely used functi...,maintenance test case test automation scree...,"['maintenance', 'test', 'case', 'test', 'autom...",building test automation framework using selen...,"['maintenance', 'test', 'case', 'test', 'autom...","['maintenance', 'test', 'case', 'test', 'autom...",5
7,"Programming Languages, Part A",University of Washington,Intermediate,4.9,https://www.coursera.org/learn/programming-lan...,This course is an introduction to the basic co...,inference ml (programming language) higher-o...,"['inference', 'ml', '(programming', 'language)...",programming languages part aprogramming langua...,"['inference', 'ml', '(programming', 'language)...","['functional', 'programming', 'pattern', 'lang...",1
12,Hacking and Patching,University of Colorado System,Advanced,3.4,https://www.coursera.org/learn/hacking-patching,"In this MOOC, you will learn how to hack web a...",Security Design design pattern web applicati...,"['security', 'design', 'design', 'pattern', 'w...",hacking and patchinghacking and patchinghackin...,"['security', 'design', 'design', 'pattern', 'w...","['security', 'design', 'design', 'pattern', 'w...",6
13,Business Statistics and Analysis Capstone,Rice University,Beginner,4.7,https://www.coursera.org/learn/business-statis...,The Business Statistics and Analysis Capstone ...,Statistical Analysis Microsoft Excel busines...,"['statistical', 'analysis', 'microsoft', 'exce...",business statistics and analysis capstonebusin...,"['statistical', 'analysis', 'microsoft', 'exce...","['statistical', 'analysis', 'microsoft', 'exce...",2
...,...,...,...,...,...,...,...,...,...,...,...,...
3448,Finance for Startups,Korea Advanced Institute of Science and Techno...,Beginner,4.6,https://www.coursera.org/learn/finance-for-sta...,Finance is one of the key ingredients for succ...,income statement Venture Capital cash flow s...,"['income', 'statement', 'venture', 'capital', ...",finance for startupsfinance for startupsfinanc...,"['income', 'statement', 'venture', 'capital', ...","['income', 'capital', 'cash', 'flow', 'account...",4
3450,Networking and Security Architecture with VMwa...,VMware,Intermediate,4.8,https://www.coursera.org/learn/networking-secu...,This 8 week online course equips learners with...,network administrator solution architect ope...,"['network', 'administrator', 'solution', 'arch...",networking and security architecture with vmwa...,"['network', 'administrator', 'solution', 'arch...","['network', 'administrator', 'solution', 'arch...",6
3464,Big Data Integration and Processing,University of California San Diego,Beginner,4.4,https://www.coursera.org/learn/big-data-integr...,"At the end of the course, you will be able to:...",Big Data Apache PostgreSQL Apache Spark an...,"['big', 'data', 'apache', 'postgresql', 'apach...",big data integration and processingbig data in...,"['big', 'data', 'apache', 'postgresql', 'apach...","['big', 'data', 'apache', 'postgresql', 'apach...",2
3478,Security Awareness Training,(ISC)�,Beginner,4.7,https://www.coursera.org/learn/security-awaren...,The security of an organization is of the utmo...,security security management multi-factor au...,"['security', 'security', 'management', 'multi-...",security awareness trainingsecurity awareness ...,"['security', 'security', 'management', 'multi-...","['security', 'security', 'management', 'authen...",6
3519,Business intelligence and data analytics: Gene...,Macquarie University,Advanced,4.6,https://www.coursera.org/learn/business-intell...,�Megatrends� heavily influence today�s organis...,analytics tableau software Business Intellig...,"['analytics', 'tableau', 'software', 'business...",business intelligence and data analytics gener...,"['analytics', 'tableau', 'software', 'business...","['analytics', 'tableau', 'software', 'business...",2

In [129]:
# filter columns field_id and skill_list_2
coursera = coursera[['field_id', 'skill_list_2']]

In [130]:
# grouped by field_id, combine skill_list_2
grouped_coursera = coursera.groupby('field_id')['skill_list_2'].agg(sum).reset_index()
grouped_coursera

   field_id                                       skill_list_2
0         1  ['inference', 'ml', '(programming', 'language)...
1         2  ['data', 'analysis', 'select', '(sql)', 'datab...
2         3  ['sketchup', 'lamp', '(software', 'bundle)', '...
3         4  ['control', '(management)', 'planning', 'proce...
4         5  ['maintenance', 'test', 'case', 'test', 'autom...
5         6  ['security', 'design', 'design', 'pattern', 'w...

In [133]:
grouped_coursera['skill_list_2'][0]

str

In [135]:
grouped_coursera['cleaned_skill_list'] = grouped_coursera['skill_list_2'].apply(
    lambda s: [word.strip('\'').replace('\\', '').replace('(', '').replace(')', '') for word in s.strip('[]').split(', ')]
)
grouped_coursera

,field_id,skill_list_2,cleaned_skill_list
0,1,"['inference', 'ml', '(programming', 'language)...","[inference, ml, programming, language, higher-..."
1,2,"['data', 'analysis', 'select', '(sql)', 'datab...","[data, analysis, select, sql, database, manage..."
2,3,"['sketchup', 'lamp', '(software', 'bundle)', '...","[sketchup, lamp, software, bundle, web, design..."
3,4,"['control', '(management)', 'planning', 'proce...","[control, management, planning, process, leade..."
4,5,"['maintenance', 'test', 'case', 'test', 'autom...","[maintenance, test, case, test, automation, sc..."
5,6,"['security', 'design', 'design', 'pattern', 'w...","[security, design, design, pattern, web, appli..."

In [136]:
# use ast to convert string to list
grouped_coursera['skill_list_2'] = grouped_coursera['skill_list_2'].apply(ast.literal_eval)

ValueError: malformed node or string: <_ast.Subscript object at 0x0000026CA9CD29D0>

In [140]:
grouped_coursera

,field_id,skill_list_2,cleaned_skill_list
0,1,"['inference', 'ml', '(programming', 'language)...","[inference, ml, programming, language, higher-..."
1,2,"['data', 'analysis', 'select', '(sql)', 'datab...","[data, analysis, select, sql, database, manage..."
2,3,"['sketchup', 'lamp', '(software', 'bundle)', '...","[sketchup, lamp, software, bundle, web, design..."
3,4,"['control', '(management)', 'planning', 'proce...","[control, management, planning, process, leade..."
4,5,"['maintenance', 'test', 'case', 'test', 'autom...","[maintenance, test, case, test, automation, sc..."
5,6,"['security', 'design', 'design', 'pattern', 'w...","[security, design, design, pattern, web, appli..."

In [141]:
grouped_all2

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [142]:
grouped_all3 = grouped_all2.copy()
grouped_all3

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [144]:
# combine grouped_all2 and grouped_coursera
grouped_all3['skill_list'] = grouped_all3['skill_list'] + grouped_coursera['cleaned_skill_list']
grouped_all3

   field_id                                         skill_list
0         1  [problem solving, programming, algorithms, pro...
1         2  [formal languages, automata theory, language t...
2         3  [user experience, interface design, usability,...
3         4  [data management, information organization, da...
4         5  [information security, cybersecurity, data pro...
5         6  [operating systems, system administration, com...

In [145]:
# saved to csv
grouped_all3.to_csv('../../static/csv/z_group_all3.csv', index=False)

In [146]:
# load csv
grouped_all3 = pd.read_csv('../../static/csv/z_group_all3.csv')

In [147]:
grouped_all3

   field_id                                         skill_list
0         1  ['problem solving', 'programming', 'algorithms...
1         2  ['formal languages', 'automata theory', 'langu...
2         3  ['user experience', 'interface design', 'usabi...
3         4  ['data management', 'information organization'...
4         5  ['information security', 'cybersecurity', 'dat...
5         6  ['operating systems', 'system administration',...